### ISSUE TITLE
Histograms don't update when changing selected attribute

### ISSUE THREAD

**Issue by warriorspot** [glue-viz/glue#1010]
GlueViz 0.7.2, Mac

When switching between histogram attributes with the same number of bins, the histogram does not redraw to reflect the data from the newly selected attribute.  I have to select a new attribute that has a different number of bins, then go back and select the attribute I originally wanted to view.

This is 100% reproducible.

**Comment by astrofrog** [comment]
I can confirm that this is indeed reproducible - though the limits also have to match between the attributes.

**Comment by warriorspot** [comment]
@astrofrog I appreciate the fast response!  I won't have time to investigate this much more, but a fix would be great.  If I do get a chance to look further and I find any more info, I'll let you know.

**Comment by astrofrog** [comment]
I've made the fix in https://github.com/glue-viz/glue/pull/1012, but still need to add a test before merging.
