### ISSUE TITLE
WARNING:root:Message signing is disabled

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1020]
This warning often appears when starting up glue:

```
WARNING:root:Message signing is disabled.  This is insecure and not recommended!
```

I think this is due to Jupyter/IPython, but I haven't figured out how to avoid it.

**Comment by jareddeutsch** [comment]
It looks like it is fixed in Jupyter 4.3.2 - https://github.com/ipython/ipykernel/pull/131. As of today, anaconda is using ipykernel 4.3.1. Looks like it should be avoided with 4.3.2.
