### ISSUE TITLE
Spectra extracting tool on polygon mode is slow

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1021]
As above, the polygon mode is much slower than the rectangle mode, sometimes it takes a few min for getting a spectra :(

**Comment by astrofrog** [comment]
It would be worth checking how many points are in the polygon - if we are adding too many points to the polygon when drawing it, this would cause it to be slow.

**Comment by PennyQ** [comment]
Ok I will start from this and keep you updated about it @astrofrog

**Comment by PennyQ** [comment]
this is fixed
