### ISSUE TITLE
save session data file not found when sharing

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1030]
The shared session now includes the absolute path for data file from the original user, while it might be better to include the data file itself or let other users to load from their local machine?

> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/decorators.py", line 38, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/decorators.py", line 23, in result
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 723, in _restore_session
>     ga = self.restore_session(file_name)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 765, in restore_session
>     ga = Application.restore_session(path)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/application_base.py", line 128, in restore_session
>     return state.object('__main__')
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 448, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/application_base.py", line 302, in **setgluestate**
>     self = cls(data_collection=context.object(rec['data']))
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 448, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 611, in _load_data_collection_2
>     result = _load_data_collection(rec, context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 602, in _load_data_collection
>     dc = DataCollection(list(map(context.object, rec['data'])))
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 454, in object
>     gen, obj = obj, next(obj)  # get the partially-constructed value...
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 690, in _load_data_3
>     result = _load_data_2(rec, context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 675, in _load_data_2
>     result = _load_data(rec, context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 647, in _load_data
>     for cid, comp in rec['components']]
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 448, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 721, in _load_component
>     return context.object(rec['log']).component(rec['log_item'])
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 448, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/data_factories/helpers.py", line 161, in __setgluestate__
>     d = load_data(rec['path'], factory=fac, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/data_factories/helpers.py", line 237, in load_data
>     d = as_list(factory(path, *_kwargs))
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/data_factories/helpers.py", line 325, in auto_data
>     fac = find_factory(filename, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/data_factories/helpers.py", line 302, in find_factory
>     is_format = df.identifier(filename, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/plugins/dendro_viewer/data_factory.py", line 23, in is_dendro
>     if is_hdf5(file):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/data_factories/hdf5.py", line 37, in is_hdf5
>     with open(filename, 'rb') as infile:
> IOError: [Errno 2] No such file or directory: u'/TerraNova/Users/agoodman/Google Drive/Nessie Paper/Data_Peretto_IRDCs/peretto_l_b'

**Comment by astrofrog** [comment]
When you save a session, you already have the option to include the data in the session file - there is a drop down menu in the window that appears when you 'save session'. Do you see it?

**Comment by astrofrog** [comment]
See [here](http://glueviz.org/en/stable/whatsnew/0.5.html#new-features) for more details
