### ISSUE TITLE
HTTP error 500 when sending bug report

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1036]
The error info is:

> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/feedback.py", line 43, in accept
>     urlopen(req)
>   File "/Users/penny/anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Users/penny/anaconda/lib/python2.7/urllib2.py", line 437, in open
>     response = meth(req, response)
>   File "/Users/penny/anaconda/lib/python2.7/urllib2.py", line 550, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/Users/penny/anaconda/lib/python2.7/urllib2.py", line 475, in error
>     return self._call_chain(_args)
>   File "/Users/penny/anaconda/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(_args)
>   File "/Users/penny/anaconda/lib/python2.7/urllib2.py", line 558, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

**Comment by astrofrog** [comment]
Should be fixed
