### ISSUE TITLE
Optional way to set contrast/bias in 2D image viewer

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1038]
Just wondering except the options in dropdown list and 'two finger' way, is there any other ways to modify the contrast/bias? Is it possible to add a hotkey or slider bar for 'easier' control?  @astrofrog 

I also feel there is a small delay when doing 'two finger' setting, not sure it's the algorithm problem or data size cause ;)

**Comment by astrofrog** [comment]
Ah I didn't know it worked with two finger - I normally use control-click! (press control and move mouse around)

**Comment by astrofrog** [comment]
We should provide ways that use sliders ideally though, since this could end up being more intuitive

**Comment by astrofrog** [comment]
The image layer artist editor (currently missing) could include settings for the colormap, limits, bias, and contrast.

**Comment by astrofrog** [comment]
This is now fixed in the latest developer version - it's possible to set contrast/bias with the normal click not right-click, and the contrast/bias settings are also available on the left in the layer options.
