### ISSUE TITLE
Show real velocity value instead of channel on 2D image viewer

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1054]
Can we show real velocity value instead of channel here? I found when I know the regions of specific velocity range then I have to try the slider bar really adjust to it ;)

![image](https://cloud.githubusercontent.com/assets/13411839/17161781/33177dec-537e-11e6-94e1-5e892e5c8d2e.png)

**Comment by PennyQ** [comment]
@astrofrog I mean the value in the text box (right bottom one), how about we put the channel to the left and real velocity value on the right (as below in DS9)? Can you show me how to do channel -> velocity transform and I could try it? 

![image](https://cloud.githubusercontent.com/assets/13411839/17302111/a9f3b886-57e8-11e6-8500-0795c1d7cbe3.png)

**Comment by astrofrog** [comment]
@PennyQ - see https://github.com/glue-viz/glue/pull/1059 - I think that the approach there might be better because in the example you show above, you can't edit the slice number, only the world coordinate? let's discuss it in https://github.com/glue-viz/glue/pull/1059
