### ISSUE TITLE
Clearer viewer title of histogram viewer

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1082]
So current title will be shown and updated with X axis label, but maybe it's better to also include dataset name. 

![image](https://cloud.githubusercontent.com/assets/13411839/17749834/69f9860a-648d-11e6-870f-7994ee2a61d0.png)

**Comment by astrofrog** [comment]
This is no longer relevant as the latest histogram viewer just has ``1D Histogram`` as the title
