### ISSUE TITLE
Do not want to start Glue in fullscreen mode

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1091]
I see that a similar issue has been raised before (#469) but it was closed without resolution nor explanation.

**Comment by astrofrog** [comment]
@pllim - on what platform does glue start up in fullscreen mode?

**Comment by pllim** [comment]
RHEL6 64-bit

**Comment by pllim** [comment]
More specifically:

```
Linux ... 2.6.32-642.3.1.el6.x86_64 #1 SMP Sun Jun 26 18:16:44 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by astrofrog** [comment]
@pllim - can you check to see if commenting out the line:

```
        self.setWindowState(Qt.WindowMaximized)
```

in ``glue/app/qt/application.py`` helps?

**Comment by pllim** [comment]
Yes, it does. But that is hardly user-friendly...

**Comment by astrofrog** [comment]
Just wanted to check if that was the culprit. Do you think this should be a command-line flag on the glue command, or it should not maximize by default?

**Comment by pllim** [comment]
I don't think it should be maximized by default. You can set the default window size to be a large percentage of available screen space if you want, but not maximized.

**Comment by astrofrog** [comment]
@pllim - do you know how to do this? If so, would you be happy to do a pull request?

**Comment by pllim** [comment]
If you mean commenting out that line, then yes, I can submit a PR.
