### ISSUE TITLE
Weird dev tagging

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1095]
When I already have `glueviz==0.9.0.dev2992` installed, I made some changes, and installed again, I get the following:

```
Finished processing dependencies for glueviz==0.9.0.dev29922992
```

I was expecting it to just overwrite the installation.

**Comment by astrofrog** [comment]
I noticed that too - weird indeed!

**Comment by pllim** [comment]
See #1099 for a fix.

**Comment by pllim** [comment]
Until the fix is merged, the workaround is to do `git clean -xdf` before `python setup.py install` again.
