### ISSUE TITLE
"World N" axis label is confusing

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1107]
As mentioned in [this comment in #1090](https://github.com/glue-viz/glue/pull/1090#issuecomment-241846123), Glue displays axes as "World 0" and "World 1" for image viewer even when WCS is not present. This is confusing for me. However, I am not sure if "X" and "Y" would be less confusing. Maybe we can discuss here on what the ideal label should be, if applicable. If no one else feels the same way, you can close this issue.

**Comment by astrofrog** [comment]
@pllim - I've been thinking about this recently - I think what's confusing is that when there is no WCS, there should only be one coordinate system (pixel), so I think we should just not include World in those cases.

**Comment by astrofrog** [comment]
I think this has been fixed since the issue was first opened.
