### ISSUE TITLE
Plotting table data

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1136]
It seems like the only way to plot table data is to use "scatter plot". I cannot find a way to turn it into a line plot. Also, would be nice to display units in the plot axis too (like #1135).

Also I can plot against indices (shown as "pixel axis" in the drop-down) but that option is not visible by default. Is this documented anywhere? I can't seem to find pages like "this is such-and-such viewer and these are the options".

**Comment by astrofrog** [comment]
Joining points with a line will be possible after https://github.com/glue-viz/glue/pull/1127

The plotting against pixel axes is not consistent across viewers at the moment, and I'll also work on that as part of #1127 (same for units).

**Comment by astrofrog** [comment]
Joining points with a line is now possible, and the histogram and scatter plot viewers now show the coordinate components in the list, so one can do the second thing you mention too.
