### ISSUE TITLE
No module named qtpy

### ISSUE THREAD

**Issue by Thomas-van-Dijk** [glue-viz/glue#1143]
Hi,

I installed using conda 
` conda install -c conda-forge glueviz`

but running glue from terminal gave me this error. 

```
    from qtpy.uic import loadUi
ImportError: No module named 'qtpy.uic'
```
Any thougths?
Thomas

**Comment by astrofrog** [comment]
@Thomas-van-Dijk - which operating system are you using?

**Comment by Thomas-van-Dijk** [comment]
ubuntu 16.04 LTS

**Comment by astrofrog** [comment]
@Thomas-van-Dijk - thanks, could you let me know the output of ``conda list``?

**Comment by Thomas-van-Dijk** [comment]
_nb_ext_conf              0.2.0                    py35_0  
alabaster                 0.7.8                    py35_0  
anaconda                  custom                   py35_0  
anaconda-client           1.4.0                    py35_0  
anaconda-navigator        1.2.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astropy                   1.2.1               np111py35_0  
babel                     2.3.3                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.4.1                    py35_0  
bitarray                  0.8.1                    py35_0  
blaze                     0.10.1                   py35_0  
bokeh                     0.12.0                   py35_0  
boto                      2.40.0                   py35_0  
bottleneck                1.1.0               np111py35_0  
cffi                      1.6.0                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.6                      py35_0  
cloudpickle               0.2.1                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
conda                     4.2.9                    py35_0  
conda-build               1.21.3                   py35_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py35_0  
contextlib2               0.5.3                    py35_0  
cryptography              1.4                      py35_0  
curl                      7.49.0                        0  
cycler                    0.10.0                   py35_0  
cython                    0.24                     py35_0  
cytoolz                   0.8.0                    py35_0  
dask                      0.10.0                   py35_0  
datashape                 0.5.2                    py35_0  
dbus                      1.10.10                       0    conda-forge
decorator                 4.0.10                   py35_0  
dill                      0.2.5                    py35_0  
Django                    1.10.1                    <pip>
docutils                  0.12                     py35_2  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_0  
et_xmlfile                1.0.1                    py35_0  
expat                     2.1.0                         2    conda-forge
fastcache                 1.0.2                    py35_1  
flask                     0.11.1                   py35_0  
flask-cors                2.1.2                    py35_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
get_terminal_size         1.0.0                    py35_0  
gettext                   0.19.7                        1    conda-forge
gevent                    1.1.1                    py35_0  
glib                      2.48.0                        4    conda-forge
glue-vispy-viewers        0.5                      py35_0    conda-forge
glueviz                   0.9.0                    py35_2    conda-forge
greenlet                  0.4.10                   py35_0  
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h5py                      2.6.0               np111py35_1  
hdf5                      1.8.16                        0  
heapdict                  1.0.0                    py35_1  
icu                       54.1                          0  
idna                      2.1                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.3.1                    py35_0  
ipython                   4.2.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                4.1.1                    py35_0  
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.2                      py35_1  
jedi                      0.9.0                    py35_1  
jinja2                    2.8                      py35_1  
jpeg                      8d                            1  
jsonschema                2.5.1                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            4.3.0                    py35_0  
jupyter_console           4.1.1                    py35_0  
jupyter_core              4.1.0                    py35_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          3    conda-forge
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxcb                    1.12                          0    conda-forge
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.11.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.6.0                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                1.5.1               np111py35_0  
mistune                   0.7.2                    py35_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py35_2  
mpmath                    0.19                     py35_1  
multipledispatch          0.4.8                    py35_0  
mysql                     5.5.24                        0  
mysqlclient               1.3.9                     <pip>
nb_anacondacloud          1.1.0                    py35_0  
nb_conda                  1.1.0                    py35_0  
nb_conda_kernels          1.0.3                    py35_0  
nbconvert                 4.2.0                    py35_0  
nbformat                  4.0.1                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.1                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  4.2.1                    py35_0  
numba                     0.26.0              np111py35_0  
numexpr                   2.6.0               np111py35_0  
numpy                     1.11.1                   py35_0  
odo                       0.5.0                    py35_1  
openpyxl                  2.3.2                    py35_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np111py35_0  
partd                     0.3.4                    py35_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py35_0  
pathlib2                  2.1.0                    py35_0  
patsy                     0.4.1                    py35_0  
pcre                      8.38                          1    conda-forge
pep8                      1.7.0                    py35_0  
pexpect                   4.0.1                    py35_0  
pickleshare               0.7.2                    py35_0  
pillow                    3.2.0                    py35_1  
pip                       8.1.2                    py35_0  
plotly                    1.12.9                   py35_0    conda-forge
ply                       3.8                      py35_0  
psutil                    4.3.0                    py35_0  
ptyprocess                0.5.1                    py35_0  
py                        1.4.31                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_1  
pycparser                 2.14                     py35_1  
pycrypto                  2.6.1                    py35_4  
pycurl                    7.43.0                   py35_0  
pyflakes                  1.2.3                    py35_0  
pygments                  2.1.3                    py35_0  
pyopengl                  3.1.0                    py35_0    conda-forge
pyopenssl                 0.16.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyqt                      4.11.3                   py35_1  
pytables                  3.2.2               np111py35_4  
pytest                    2.9.2                    py35_0  
python                    3.5.2                         0  
python-dateutil           2.5.3                    py35_0  
pytz                      2016.4                   py35_0  
pyyaml                    3.11                     py35_4  
pyzmq                     15.2.0                   py35_1  
qt                        4.8.6                         3  
qtconsole                 4.2.1                    py35_0  
qtpy                      1.0.2                    py35_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0  
requests                  2.10.0                   py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14                  py35_0  
scikit-image              0.12.3              np111py35_1  
scikit-learn              0.17.1              np111py35_2  
scipy                     0.17.1              np111py35_1  
setuptools                23.0.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.16.5                   py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.4.1                    py35_0  
sphinx_rtd_theme          0.1.9                    py35_0  
spyder                    2.3.9                    py35_0  
sqlalchemy                1.0.13                   py35_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py35_1  
sympy                     1.0                      py35_0  
terminado                 0.6                      py35_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py35_0  
tornado                   4.3                      py35_1  
traitlets                 4.2.1                    py35_0  
unicodecsv                0.14.1                   py35_0  
werkzeug                  0.11.10                  py35_0  
wheel                     0.29.0                   py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.2                    py35_0  
xlwt                      1.1.2                    py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3

**Comment by astrofrog** [comment]
@Thomas-van-Dijk - ah, I see the issue, the version of qtpy is too old - try doing:

```
conda install -c conda-forge qtpy=1.1.1
```

Does this help? If so, I'll make sure I update the minimum version specified in the conda package.

**Comment by Thomas-van-Dijk** [comment]
@astrofrog This helps indeed. Thanks for the fast response!

**Comment by astrofrog** [comment]
Just for information, I've opened a pull request to make sure the conda package includes 1.1.1 as a minimum version for QtPy: https://github.com/conda-forge/glueviz-feedstock/pull/11

Thanks for the report!
