### ISSUE TITLE
Add a .meta attribute to Data objects

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1147]

**Comment by mattjhill** [comment]
I'm happy to try to get this implemented.  Does anything need to be done besides adding `self.meta = OrderedDict()` to `Data.__init__()`?

In the Astropy Table data factory I can easily set the Data.meta to be the same as the Table.meta. Not sure what is relevant for other data types.

**Comment by astrofrog** [comment]
Fixed in #1155. Loaders can decide what to put in there, and we don't need to worry about other loaders yet.
