### ISSUE TITLE
Failed to restore session __init__() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1149]
@astrofrog I tried to open a session (data not included) and get an error above, do you know how to solve this? More details lists below, thanks!

> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/decorators.py", line 53, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 730, in _restore_session
>     ga = self.restore_session(file_name)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 772, in restore_session
>     ga = Application.restore_session(path)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/application_base.py", line 128, in restore_session
>     return state.object('__main__')
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 456, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/application_base.py", line 302, in **setgluestate**
>     self = cls(data_collection=context.object(rec['data']))
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 456, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 634, in _load_data_collection_3
>     result = _load_data_collection_2(rec, context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 626, in _load_data_collection_2
>     result = _load_data_collection(rec, context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 617, in _load_data_collection
>     dc = DataCollection(list(map(context.object, rec['data'])))
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 462, in object
>     gen, obj = obj, next(obj)  # get the partially-constructed value...
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 730, in _load_data_4
>     result = _load_data_2(rec, context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 696, in _load_data_2
>     result = _load_data(rec, context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 688, in _load_data
>     result.add_subset(context.object(s))
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 469, in object
>     for _ in gen:  # ... and finish constructing it
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/subset_group.py", line 86, in __setgluestate__
>     self.group = context.object(rec['group'])
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 469, in object
>     for _ in gen:  # ... and finish constructing it
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/subset_group.py", line 193, in **setgluestate**
>     result.subset_state = context.object(rec['state'])
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 456, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/subset.py", line 914, in **setgluestate**
>     state = cls(indices=context.object(rec['indices']))
> TypeError: **init**() takes exactly 3 arguments (2 given)

**Comment by astrofrog** [comment]
This will be fixed by https://github.com/glue-viz/glue-vispy-viewers/pull/214
