### ISSUE TITLE
Allow WCSCoordinates to be initialized with only a WCS object

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1170]
At the moment, WCSCoordinates **requires** a header, but we should change this so that a WCS object alone should be enough.

**Comment by pllim** [comment]
The class docstring says, "This class does not take into account distortions." Does it mean the distortion is ignored or the information is actually lost?

**Comment by pllim** [comment]
Is there a reason not to put `from astropy.wcs import WCS` at the top of the module?
