### ISSUE TITLE
Attribute name changed to be same after 'linking data'

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1173]
It's shown as below, both the column names on data sets (left two panels) and the current links (right one panel) changed to be the same (col3 - DEC and col1 - RA should be the correct name)

![image](https://cloud.githubusercontent.com/assets/13411839/20360956/d09565e2-ac03-11e6-8499-d2cd542fe527.png)

@astrofrog Do we have an issue for this bug? This confused users after linking data that there is no way which linking attribute is which, thanks!

**Comment by astrofrog** [comment]
This should now be fixed!
