### ISSUE TITLE
Glue crashed on MacOS on second screen

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1184]
I got a warning dialog as below, right after open glue in terminal
![image](https://cloud.githubusercontent.com/assets/13411839/20656315/43a96742-b4f9-11e6-95e1-447e34ae77c5.png)

Error shows:
> ➜  glue-3d-viewer git:(master) ✗ glue
/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.10.0.dev3176-py2.7.egg/glue/external/qt.py:6: GlueDeprecationWarning: The glue.external.qt subpackage is deprecated - see the v0.9 release announcement for more details
  "release announcement for more details", GlueDeprecationWarning)
[1]    5948 segmentation fault  glue

Not sure if Glue conflicts with other programs or it's a new bug, I will keep updated here

**Comment by astrofrog** [comment]
If it happens again, can you click on 'report' and paste the full output of the report here?

**Comment by astrofrog** [comment]
I'll close this for now, open a new issue if you see this again though!
