### ISSUE TITLE
Selected points not showing up on linked image viewer

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1199]
@astrofrog , I am using data from [User Training in JWST Data Analysis II](https://jwst.stsci.edu/events/events-area/stsci-events-listing-container/user-training-in-jwst-data-analysis-ii), in the `NIRCam_Simulated` folder. I linked `simulated_nircam_1.fits` and `star_physical_info.txt` by RA and DEC. The image is displayed in image viewer and the table is displayed as scatter plot (mass vs distance).

When I select ROI on image viewer, I can see points highlighted on scatter plot. But when I select ROI on scatter plot, nothing shows up on image. Glue's demo video shows that I am supposed to see something. I can't find where to set the ROI highlight parameters on the GUI (e.g., maybe make the point size larger on image viewer). Is this a bug or am I missing something?

I am using Windows 7 (64-bit).

**Comment by astrofrog** [comment]
I hope I replied via some other channel, but if not: since the data is linked by spatial coordinates, only selections in spatial coordinates can be propagated between the linked datasets, so this is expected behavior.
