### ISSUE TITLE
Blank Error window appear after selecting "plotly", under Glueviz application.

### ISSUE THREAD

**Issue by Usama23** [glue-viz/glue#1202]
Os: Windows
Anaconda Navigator 1.4.rc1

**Steps to Reproduce:**
     1: Login to Anaconda Navigator.
     2: Under the Home tab, install and launch Glueviz app.
     3:  Under the app menu from top, select "File" and then select "Export" from drop down.
     4: And then select "Plotly".

**Actual Result:**
  When click on Plotly, Blank error pop up window appear.Which stuck the app, because error pop up window has no option to close the error.

**Expected Result:**
     When click on Plotly, it should open with specific related window successfully.

![screenshot_35](https://cloud.githubusercontent.com/assets/21064099/21723747/7619c66c-d453-11e6-8ddc-f2a9bf7eaf39.png)

![screenshot_34](https://cloud.githubusercontent.com/assets/21064099/21723748/761b50a4-d453-11e6-83af-ecc59a7c9b2f.png)

**Comment by astrofrog** [comment]
@Usama23 - can you send the information that is in Help -> Version Information? Thanks!

**Comment by Usama23** [comment]
@astrofrog sure....

**Version Information**

Glue: 0.9.1
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.0
PySide: Not installed
qtpy: 1.1.2
setuptools: 27.2.0
numpy: 1.11.1
matplotlib: 1.5.3
pandas: 0.18.1
astropy: 1.2.1
dill: 0.2.5
h5py: 2.6.0
xlrd: unknown version
scipy: 0.18.1
skimage: 0.12.3
IPython: 5.1.0
ipykernel: 4.5.0
qtconsole: 4.2.1
traitlets: 4.3.0
pygments: 2.1.3
zmq: 15.4.0
pyavm: Not installed
spectral_cube: Not installed
ginga: Not installed
astrodendro: Not installed
mock: Not installed
pytest: 2.9.2
plotly: Not installed

**Comment by astrofrog** [comment]
@Usama23 - this should be fixed in glueviz 0.10.x I believe - please feel free to re-open if you are still seeing this
