### ISSUE TITLE
Fail to project selection on histogram across data sets

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1210]
@astrofrog As shown in the example figure below, selection on histogram from one data set (two views on the right) couldn't be projected to the other glue-ed data set (left one view). While selection on image view works well (although quite slow).

I suspected there is a linking deadlock on histogram selection functions.

![image](https://cloud.githubusercontent.com/assets/13411839/22185806/5e092f7c-e0ba-11e6-81f3-bf63e9a60296.png)

**Comment by astrofrog** [comment]
I think we discussed this on a telecon back then - basically this is not a bug but just due to how linking works (only spatial selections would propagate to the spatial view of another dataset).
