### ISSUE TITLE
Dendrogram view not work on dev version

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1213]
1) Two menu bars get shown at the same time
2) Selection from dendrogram structure not get shown on the image

![image](https://cloud.githubusercontent.com/assets/13411839/22524061/b68a89d4-e88f-11e6-9682-c75901c13c5e.png)

**Comment by astrofrog** [comment]
I've fixed the duplicate toolbar in #1237 - I do find the selections work though, I think the leaf you selected is too small to see in the image. Try selecting more of the tree like:

<img width="1131" alt="screen shot 2017-02-10 at 15 28 10" src="https://cloud.githubusercontent.com/assets/314716/22832370/a634fe6c-efa5-11e6-8437-676fcc66b301.png">
