### ISSUE TITLE
'CanvasBackendDesktop' object has no attribute 'setFormat'

### ISSUE THREAD

**Issue by ax3l** [glue-viz/glue#1279]
Hi!

First of all: I love glue-viz, it's wonderful :)

One problem I am stumbling upon with 3D scatter plots and PyQt5 (I took care not to have PyQt4 or PySide installed simultaneously) is:

```
  File ".local/lib/python3.4/site-packages/glue_vispy_viewers/extern/vispy/app/backends/_qt.py", line 694, in _init_specific
    self.setFormat(glformat)
AttributeError: 'CanvasBackendDesktop' object has no attribute 'setFormat'
```

Is this a known issue?
I could not find anything about it googling it.

I am running
```
Glue: 0.10.2
PyQt4: Not installed
PyQt5: PyQt: 5.3.2 - Qt: 5.3.2
PySide: Not installed
qtpy: 1.2.1
setuptools: 32.3.1
numpy: 1.12.0
matplotlib: 2.0.0
pandas: 0.14.1
astropy: 1.3.2
dill: 0.2.6
h5py: 2.6.0
xlrd: 1.0.0
glue_vispy_viewers: 0.7.2
IPython: 5.1.0
qtconsole: 4.2.1
ipykernel: 4.3.1
traitlets: 4.3.1
pygments: 2.1.3
zmq: 15.2.0
scipy: 0.19.0
skimage: 0.10.1
pyavm: Not installed
spectral_cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: Not installed
plotly: 2.0.6
```

Thanks a lot!

**Comment by astrofrog** [comment]
@ax3l - could you try and update to a more recent version of Qt 5, e.g. 5.6, to see if this fixes the issue? (if so I will try and make the exact Qt 5 version requirement more explicit)

**Comment by astrofrog** [comment]
We now require PyQt 5.6 or later which should fix this.

**Comment by ax3l** [comment]
Thanks for the heads up! That is great news!
