### ISSUE TITLE
IPython Button Disappears After Opening Saved Session (glue-viz 0.10.4)

### ISSUE THREAD

**Issue by uacwoap** [glue-viz/glue#1294]
Before:
![glue-before](https://cloud.githubusercontent.com/assets/28989776/26513202/37e68e9a-4238-11e7-9500-18911d266ce3.png)

After:
![glue-after](https://cloud.githubusercontent.com/assets/28989776/26513209/45d66b92-4238-11e7-821a-6cd2a32bc8df.png)

Version Info:
Glue: 0.10.4
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.2
PySide: Not installed
qtpy: 1.2.1
setuptools: 27.2.0
numpy: 1.12.1
matplotlib: 2.0.2
pandas: 0.20.1
astropy: 1.3.2
dill: 0.2.6
h5py: 2.7.0
xlrd: 1.0.0
glue_vispy_viewers: 0.7.2
IPython: 6.0.0
qtconsole: 4.3.0
ipykernel: 4.6.1
traitlets: 4.3.2
pygments: 2.2.0
zmq: 16.0.2
scipy: 0.19.0
skimage: 0.13.0
pyavm: Not installed
spectral_cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: Not installed
plotly: 1.12.9

**Comment by astrofrog** [comment]
This is fixed in the latest developer version and will be fixed in v0.11

**Comment by majkelx** [comment]
Is there some workaround? 
I'm not allowed to install new version on computer I'm working on, button disappeared, i have large session in work and cannot finish processing data...
