### ISSUE TITLE
2D scatter plot colored by a third component?

### ISSUE THREAD

**Issue by shichuzhu** [glue-viz/glue#1301]
Is it possible to add an option, or how can I achieve with custom coding, that when creating a 2D scatter plot, I can color the dots based on a third component? The subset layers would thus have to be distinguished solely by different scatter symbols.

**Comment by astrofrog** [comment]
This is coming very soon! I'll post an update here once it is available.

**Comment by astrofrog** [comment]
@shichuzhu - this is now available in the developer version and will be in the v0.11 release!
