### ISSUE TITLE
loading of unstructured numpy arrays

### ISSUE THREAD

**Issue by underchemist** [glue-viz/glue#1307]
Hi,

I was just experimenting with glueviz and dumped some of my data into a .npy file only to find that glueviz had trouble loading it! When loading an numpy array saved to a .npy file I got the following traceback from loading the data in glueviz
```
Error message: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\glue\dialogs\data_wizard\qt\data_wizard_dialog.py", line 38, in data_wizard
    result = gdd.load_data()
  File "D:\Anaconda3\lib\site-packages\glue\dialogs\data_wizard\qt\data_wizard_dialog.py", line 109, in load_data
    d = load_data(path, factory=fac.function)
  File "D:\Anaconda3\lib\site-packages\glue\core\data_factories\helpers.py", line 237, in load_data
    d = as_list(factory(path, **kwargs))
  File "D:\Anaconda3\lib\site-packages\glue\core\data_factories\helpers.py", line 330, in auto_data
    return fac(filename, *args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\glue\core\data_factories\npy.py", line 39, in npy_reader
    for name in npy_data.dtype.names:
TypeError: 'NoneType' object is not iterable
```

I checked [glue/glue/core/data_factories/npy.py](https://github.com/glue-viz/glue/blob/master/glue/core/data_factories/npy.py) and saw the ValueError that mentions currently only structured numpy arrays are supported
 
``` python
if not hasattr(npy_data.dtype, 'names'):
        raise ValueError("Numpy save file loading currently only supports structured"
                         " arrays, e.g., with specified names.")
```

I didn't realize you could have unstructured or structured arrays in numpy so I looked into it and found a pretty basic workaround in my case that took my input of a 230x230x512 array of float32 values and copied it in a structured way
```python
import numpy as np
from np.random import rand
a = rand(230, 230, 512) # unstructured dummy data
b = np.array(a, dtype='float32, float32, float32') # structured copy of a
np.save('filesave1.npy', a)
np.save('filesave2.npy', b) # loadable by glueviz
```
However, I found all this not due to the ValueError I quoted above but because an unstructured multidimensional numpy array still has a names attribute, it is just Nonetype, which cannot be iterated on as it does further down in the loader function.
```python
for name in npy_data.dtype.names:
        comp = Component.autotyped(npy_data[name])
        d.add_component(comp, label=name)
```

### suggestion?

Since an unstructured array still has a nonempty name (`a.dtype.name` in my example above returns `'float32'`) attribute, if input file is unstructured and thus names is Nonetype, you could map the dtype of name and structure the dimensions of your unstructure input array.

At the very least, the if statement should be changed to catch the Nonetype of the names attribute so you get the actual ValueError exception raised.

**Comment by astrofrog** [comment]
@underchemist - thanks for reporting the issue - I think the best way to fix this would be that if ``dtype.names`` is None, we just load the array into a single component with name ``array``. Would you be interested in trying to do a pull request to implement this? If so let me know if you need any help.

**Comment by underchemist** [comment]
That sounds pretty simple I'll take a stab at it!
