### ISSUE TITLE
Update Astropy affiliated package info

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1335]
As requested by @mwcraig, please update `glueviz`'s entry in the link given below.

"Please take a look at the information for your affiliated package at https://github.com/mwcraig/astropy-affiliated-numfocus-blog and edit the yml file there to add a bit more information information about your package: a representative image, a link to educational materials (e.g. a notebook or tutorial or ...) and an update of your packages description, if it is out of date or missing." -- Matt Craig

**Comment by astrofrog** [comment]
@pllim @mwcraig - is it too late for this?

**Comment by pllim** [comment]
It's @mwcraig 's call.

**Comment by mwcraig** [comment]
The numfocus article has been published, but if there are corrections to make to the yaml at the repo please go ahead.

**Comment by astrofrog** [comment]
Just saw the article and it looks good, thanks!
