### ISSUE TITLE
Make the spectra tool view non-standalone 

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1350]
So if you linked two image and want to get the spectra from the same region on both views, it's better to subtract spectra from the subsets. 

Also, we should change the window title of spectra view to match dataset, now simply showed as 'profile'.

**Comment by PennyQ** [comment]
In this way, the selection in spectra view can also be sync between linked datasets.

**Comment by astrofrog** [comment]
Done in #1635
