### ISSUE TITLE
CASA image loader missing in current version?

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1351]
@astrofrog I couldn't find the CASA PPV cube option when loading the dataset, as it was there before. Did you change the name or it's removed? Thanks!

![image](https://user-images.githubusercontent.com/13411839/28382278-9770fde6-6c8b-11e7-9c06-e3ac5e434613.png)

**Comment by astrofrog** [comment]
Can you install the spectral-cube package and see if it comes back?

**Comment by PennyQ** [comment]
@astrofrog Yes installing the spectral-cube package works, thanks!
