### ISSUE TITLE
Alternative Download / Standalone for Windows

### ISSUE THREAD

**Issue by IvanNFZ** [glue-viz/glue#1353]
Because of corporate firewall i cant use Anaconda Navigator to Download glueviz. Is there any other possibilities to get glueviz? A standalone version is only for Mac available.
Thanks!

**Comment by astrofrog** [comment]
@IvanNFZ - unfortunately there is no simple download for Windows at the moment. I will continue to explore options for this though.

**Comment by astrofrog** [comment]
I'm going to close this in favor of https://github.com/glue-viz/glue/issues/146
