### ISSUE TITLE
More flexible FITS loading

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#136]
The fits image loader currently requires all fits extensions to have identical shape. This is too strict a requirement, and should be relaxed.

One possible option:

The fits factory returns a list of 1 or more Data objects, depending on how many distinct array sizes are in the fits file. The Glue GUI then brings up a secondary window that shows the new data objects and their components, allowing the user to deselect or rename each piece.

**Comment by stscieisenhamer** [comment]
FYI for you'all: We're currently in a sprint to define/prototype tools for IFU and other data that will be in cube or >3 dimensional datasets. Many of the datasets come in vary heterogeneous FITS files. To help in quickly viewing such datasets, I've started developing a *generic FITS* data factory that automates some of what is discussed here. Hardly ready for prime time but wanted to point it out, hoping for any suggestions, etc.
This can be found in spacetelescope/cube-tools/glue_loader

**Comment by astrofrog** [comment]
Part of this was already implemented by @stscieisenhamer (thanks!) and I've opened a new more general issue to mention having a window that can be used to preview what is going to be read and deselect things that aren't interesting. So for any discussions about that, see https://github.com/glue-viz/glue/issues/980.
