### ISSUE TITLE
Extra "sep" text in menu separator

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1393]
![untitled](https://user-images.githubusercontent.com/2090236/29730402-093ab8c4-89ae-11e7-89d1-0b22e7b39edd.png)

I don't think the "sep" text is supposed to be there. Separators in other menus look fine.

**Comment by astrofrog** [comment]
Huh weird I thought I fixed it in https://github.com/glue-viz/glue/pull/1232 - will investigate!

**Comment by pllim** [comment]
I installed 0.11 from pip.

**Comment by astrofrog** [comment]
Oops it turns out this bug occurred in two places and I only fixed one before... See https://github.com/glue-viz/glue/pull/1394 for the fix.

**Comment by pllim** [comment]
Thanks for the quick fix!
