### ISSUE TITLE
conda version of PyQt5 on Linux does not include OpenGL support

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1395]
When I attempt to do 3D rendering with Glue 0.11 on RHEL7 using Anaconda, I get this pop-up message:
```
The conda version of PyQt5 on Linux does not include OpenGL
support, which means that the 3D viewers will not work. The
easiest way to solve this is to manually downgrade to PyQt4. This
can normally be done with 'conda install pyqt=4'.
```

Will OpenGL support be added for Qt5 in the future on Linux? Is there a workaround that does not require a downgrade?

**Comment by astrofrog** [comment]
See https://github.com/ContinuumIO/anaconda-issues/issues/1267 - this is an issue with the conda package for qt5. It might be worth trying the pyqt5 package from conda-forge to see if it works any better.

**Comment by pllim** [comment]
I did a
```
conda uninstall pyqt --force
```
and then
```
conda install pyqt -c conda-forge
```
but still get the same message. Ah, well. 😢 

```
$ conda list qt
pyqt                      5.6.0                    py35_4    conda-forge
pyqtgraph                 0.10.0                   py35_0    http://ssb.stsci.edu/astroconda
qt                        5.6.2                         4  
qtconsole                 4.3.0                    py35_0  
qtpy                      1.2.1                    py35_0  
```

**Comment by astrofrog** [comment]
@pllim - it may be at the qt level, so you could try and do the same for qt

**Comment by pllim** [comment]
Nope. 😢 

```
pyqt                      5.6.0                    py35_4    conda-forge
pyqtgraph                 0.10.0                   py35_0    http://ssb.stsci.edu/astroconda
qt                        5.6.2                         3    conda-forge
qtconsole                 4.3.0                    py35_0  
qtpy                      1.2.1                    py35_0  
```

**Comment by astrofrog** [comment]
This should be fixed - see http://docs.glueviz.org/en/stable/known_issues.html#d-viewers-not-working-on-linux-with-pyqt5 - but please re-open if it's not fixed.

**Comment by pscicluna** [comment]
I'm getting an occurrence of this issue on fedora 34 with a new install of glue in a clean conda environment with python 3.9. Following the docs, I attempted to update conda, then update all packages, but the versions of pyqt, qt and qtpy do not appear to have changed from the previous (up to date!) versions. No required dependencies seem to be missing. Here are the current versions:

```
Name                    Version                   Build     Channel
pyqt                      5.9.2            py39h2531618_6  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.3.0              pyhd3eb1b0_0  
qtpy                      2.0.1              pyhd3eb1b0_0  
```
Do you have any idea why this might have come back?
