### ISSUE TITLE
Facet subset bug: bin number not a multiple of steps will mess up the segementation

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1404]
I create faceted subsets with steps=5, low=1, high=6, parameter=RV, the correct result is shown with the default bin=15 as:
![image](https://user-images.githubusercontent.com/13411839/30400609-63771ec6-98a5-11e7-95a6-78209f28855a.png)

While when bin number is set not a multiple of steps (e.g. bin=16 as below), the segmentation is messed up:
![image](https://user-images.githubusercontent.com/13411839/30400757-ef2e07a4-98a5-11e7-8e3d-792b3f3b1819.png)

Should we keep bin number only be multiple to the steps? Thanks! @astrofrog

**Comment by astrofrog** [comment]
This is not actually a bug - there's no way to guarantee that the segmentation will be made using the same number of bins in the histogram, and the histogram shown is correct (that is, if you add e.g. the two colors in the fourth bin, you get the total number given by the black histogram).
