### ISSUE TITLE
3D Selection Broken in Latest Stable and Developer Versions?

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1406]
I am unable to make any 3D selection and have it translate to any other viewers, like the 2D image viewer. No errors are raised, however. It works fine the other way (2D to 3D).

**Comment by astrofrog** [comment]
@catherinezucker - can you show a screenshot?

**Comment by catherinezucker** [comment]
@astrofrog -- I've made a video hopefully showing the issue. 

https://www.dropbox.com/s/s2op5d12uebh175/Glue_3D_Selection_Test.mov?dl=0

I make a selection in 2D and it shows up in the 3D cube, but even when I select the whole 3D cube nothing shows in the 2D image. Hopefully this isn't user error on my part? If it is, could you tell me what I did wrong? I feel like I have made 3D to 2D selections before the viewer update and it worked fine. Thanks so much! The error that appears in the error console is just a blank keyword warning and completely unrelated:

WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]

**Comment by catherinezucker** [comment]
Sorry, @astrofrog. I just talked to Alyssa and Penny and I found out that the 3D volume rendering selection being mapped to a 2D image hasn't been implemented yet, so this isn't actually a bug. I just misremembered!

**Comment by astrofrog** [comment]
Sorry for not replying sooner, and glad this is not a real bug! We do need to figure out a good mapping from 3D to 2D though 😄
