### ISSUE TITLE
Repeated layers of facet subsets in the Plot Layer Panel

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1408]
After creating faceted subsets, all newly created subsets will be added to the plot layers, which is very useful! 

But one issue is that those are not able to display (shown as grey in the figure below) are also automatically added, and can’t be removed from the list. 

The same problem also happened when I create a subset by using iPython terminal with 
> subset_group = dc.new_subset_group(label, state)

<img width="335" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/13411839/30988703-24ff982e-a469-11e7-9d0c-52b0b03f947d.png">

**Comment by astrofrog** [comment]
I think this has been fixed since it was reported - disabled layers can now be selected and removed
