### ISSUE TITLE
No Drop list for Data Viewer

### ISSUE THREAD

**Issue by vermashresth** [glue-viz/glue#1411]
When adding new dataset into visualization dashboard, there is only text field and no drop down menu. Typing any field value gives an error in console.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/zmq/utils/garbage.py", line 52, in run
    msg = s.recv()
  File "socket.pyx", line 622, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5560)
  File "socket.pyx", line 656, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5380)
  File "socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1758)
  File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6058)
zmq.error.ZMQError: Interrupted system call

Traceback (most recent call last):
  File "/home/petrichor/.local/lib/python3.4/site-packages/glue/app/qt/mdi_area.py", line 61, in dropEvent
    new_layer(layer)
  File "/home/petrichor/.local/lib/python3.4/site-packages/glue/app/qt/mdi_area.py", line 51, in new_layer
    self._application.choose_new_data_viewer(layer)
  File "/home/petrichor/.local/lib/python3.4/site-packages/glue/app/qt/application.py", line 753, in choose_new_data_viewer
    default=default, sort=True)
  File "/home/petrichor/.local/lib/python3.4/site-packages/glue/utils/qt/dialogs.py", line 59, in pick_class
    return pick_item(classes, choices, **kwargs)
  File "/home/petrichor/.local/lib/python3.4/site-packages/glue/utils/qt/dialogs.py", line 35, in pick_item
    index = labels.index(str(choice))
ValueError: '2D Image Viewer' is not in list

The first error appears whenever new dataset is loaded. Second error appears after choosing new data viewer.

Running glue on python3 with PyQt4

**Comment by astrofrog** [comment]
@vermashresth - thanks for the bug report and sorry about the issue. Can you start glue by typing:

```
glue -v
```

and letting me know the output?

**Comment by vermashresth** [comment]
Hi
This is the output

INFO:glue:Input arguments: ['/home/petrichor/.local/bin/glue', '-v']
INFO:glue:Loading external plugins using setuptools==3.3
INFO:glue:Loading plugin fits_format failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin scatter_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin spectrum_tool failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin pv_slicer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin export_d3po failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin data_exporters failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin table_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin coordinate_helpers failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin histogram_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin spectral_cube failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin export_plotly failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin dendro_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin image_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin vispy_scatter failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin vispy_volume failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading settings from /home/petrichor/.glue/settings.cfg
INFO:glue.core.hub:Subscribing DataCollection (0 data sets)
	 to DataAddComponentMessage
INFO:glue.core.hub:Subscribing <glue.core.link_manager.LinkManager object at 0x7f55eaa3a518> to DataCollectionDeleteMessage
INFO:glue:Loading external plugins using setuptools==3.3
INFO:glue:Loading plugin fits_format failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin scatter_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin spectrum_tool failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin pv_slicer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin export_d3po failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin data_exporters failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin table_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin coordinate_helpers failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin histogram_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin spectral_cube failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin export_plotly failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin dendro_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin image_viewer failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin vispy_scatter failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading plugin vispy_volume failed (Exception: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.10')))
INFO:glue:Loading settings from /home/petrichor/.glue/settings.cfg
INFO:glue.core.hub:Subscribing <glue.core.qt.data_collection_model.DataCollectionModel object at 0x7f55ea85ec18> to DataCollectionDeleteMessage
INFO:glue.core.hub:Subscribing <glue.core.qt.data_collection_model.DataCollectionModel object at 0x7f55ea85ec18> to SubsetDeleteMessage
INFO:glue.core.hub:Subscribing <glue.core.qt.data_collection_model.DataCollectionModel object at 0x7f55ea85ec18> to DataCollectionAddMessage
INFO:glue.core.hub:Subscribing <glue.core.qt.data_collection_model.DataCollectionModel object at 0x7f55ea85ec18> to SubsetCreateMessage
INFO:glue.core.hub:Subscribing <glue.core.qt.data_collection_model.DataCollectionView object at 0x7f55ea842798> to Message

**Comment by astrofrog** [comment]
@vermashresth - it looks like an issue unrelated to glue but your version of the six package is too old. You can try updating it with:

```
pip install six --upgrade
```

Does this solve the issue?

**Comment by vermashresth** [comment]
@astrofrog  Thanks, I updated six, setuptools and dateutils, and it works fine now.
Is there any way we can check these requirements during installation?

**Comment by astrofrog** [comment]
@vermashresth - glue doesn't actually require six directly, I think it's likely this was due to one of glue's dependencies not having declared its dependencies correctly. But I'll investigate to see if there is anything we can do to avoid this. In any case, great that it works now!
