### ISSUE TITLE
Issue overlaying (l,b,v) scatterpoints in 3D Spectral Cube Volume Rendering

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1413]
Hi Tom,

Alyssa has already sent an email about this, but there is an issue with embedding 3D scatter points in the 3D volume renderings in the latest stable and developer versions of glue. All the spatial coordinates are aligned but the velocities are shifted to below the lower bound on the velocity axis for the cube (as in the attached screenshot).

Thanks,
Catherine

<img width="1436" alt="screen shot 2017-10-05 at 12 01 33 am" src="https://user-images.githubusercontent.com/18339657/31210484-97fbb1ae-a960-11e7-9c0f-32514822ef42.png">

**Comment by astrofrog** [comment]
We eventually determined this was due to a mismatch of units
