### ISSUE TITLE
Bug: no response for glue under the advanced linking mode 

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1414]
Clicking the 'glue' button won't add link pairs under the advanced mode (basically no response after clicking the button), the basic linking mode works well.

Glue: 0.11.1
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.2
PySide: Not installed
qtpy: 1.3.1
setuptools: 36.5.0.post20170921
numpy: 1.13.1
matplotlib: 2.0.2
pandas: 0.20.3
astropy: 2.0.2
dill: 0.2.6
h5py: 2.7.0
xlrd: 1.1.0
glue_vispy_viewers: 0.9.dev0
IPython: 5.4.1
qtconsole: 4.3.1
ipykernel: 4.6.1
traitlets: 4.3.2
pygments: 2.2.0
zmq: 16.0.2
scipy: 0.19.1
skimage: 0.13.0
pyavm: Not installed
spectral_cube: 0.4.0
astrodendro: Not installed
mock: Not installed
pytest: 3.2.1
plotly: 2.0.15

 @astrofrog Please let me know if it's fixed in the latest dev version of glue...

**Comment by astrofrog** [comment]
@PennyQ - can you show a screenshot of this?
