### ISSUE TITLE
Anaconda Support

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#145]
This issue branches off #140 

Anaconda includes PySide, but not pyuic and pyrcc. Until such tools are included, we should probably have a second repo with pre-generated qt files.

**Comment by gautam1168** [comment]
Hi,

I have a small gui written in PySide and PyQt and I need to display some icons. But without the executables to compile the qrc files this seems to be a difficult problem to overcome. I looked at glue but it seems to be solving another problem of compiling the ui files which I am not using. Is there a way I can use glue to compile my qrc file? If not then can you suggest a way to solve this problem? (Anaconda does provide the pyrcc4 and pyside-rcc executables now, but they are missing in the mac version).

**Comment by ChrisBeaumont** [comment]
hi Guarav

We moved away from using qrc files in Glue because of missing anaconda
support. You can take a look at the "get_icon" function in glue.qt.qtutil
to see how we load icons. Basically we load individual pngs from disk
instead of from a compiled qrc file

Cheers,
Chris

**Comment by ChrisBeaumont** [comment]
(Sorry for the name typo! Typing on an iphone)
