### ISSUE TITLE
*Feature Request*--Option to have single cell spectrum extractor based on mouse click

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1483]
For the spectrum extractor tool the current options are rectangle, circle, and polygon. However, it has come up a recently (via Mark Heyer) that it would be very useful to also have a "mouse click" option where you can click around a 2D image and extract the spectrum for a single cell many times over. I know this can technically be accomplished via the circle function (with a radius of 0.5 pixels) but it is cumbersome to have to keep remaking the circle, or dragging around the current circle you already have. So if it is relatively easy to implement, a fourth tab in the dropbox spectrum extractor menu with a mouse click feature would be very useful. I can also try implementing this myself in future and maybe submitting a pull request!

**Comment by astrofrog** [comment]
Done in https://github.com/glue-viz/glue/pull/1619!
