### ISSUE TITLE
Scatter size incorrect when value < min

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1486]
When the min of the linear scatter point size is larger than the min values in the data, the size goes negative instead of being zero.

**Comment by sakshambassi** [comment]
Hi, I would like to help to solve this issue, can I get some more information and which files to look in to?

**Comment by astrofrog** [comment]
@sakshambassi - sorry for the delay, I had to investigate this since I wasn't sure what the issue was. Since it's easy I've just gone ahead and fixed it.
