### ISSUE TITLE
Graph no longer shows date-time axis correctly

### ISSUE THREAD

**Issue by rsangole** [glue-viz/glue#1490]
I submitted this Q on [stackoverflow](https://stackoverflow.com/questions/47817168/glueviz-not-labeling-date-time-correctly); but @ChrisBeaumont thinks it might be a bug. Thus, raising an issue here.

**Situation**

When I plot data using glueviz, a datetime64 column is not being plotted correctly. Refer to x-axis in this figure:

![figure_0](https://user-images.githubusercontent.com/6344050/34007909-86373e36-e0d1-11e7-9d9b-912f7b7110b3.png)

Oddly enough, a few days ago, glueviz plotted date-time just fine. Refer to the x-axis in:

![figure_1](https://user-images.githubusercontent.com/6344050/34007910-870695c8-e0d1-11e7-84eb-e5153c786367.png)

Between then and now, I did update all my packages using conda, but apart from that, no other changes I can recall.

Any ideas?

**Code**

Here is sample code:

```
from glue import qglue
import pandas as pd
from numpy import random

dataf = pd.DataFrame({})
dataf['date']=pd.date_range('1/1/2011', periods=72, freq='H')
dataf['value']=random.randint(0,10,72)

qglue(df=dataf)
```

**Comment by astrofrog** [comment]
@rsangole - thanks for reporting this! I'll investigate and report back tomorrow :)

**Comment by rsangole** [comment]
An update:

I downgraded glue-core and glueviz to 0.10.4 this morning. I see the glueviz GUI interface to be the older one (different button styles etc), but I get the exact same problem:

![image](https://user-images.githubusercontent.com/6344050/34051222-b9a43e80-e18b-11e7-93a1-4e1cea45f088.png)

Is this a dependency issue with some other package I've updated?

**Comment by rsangole** [comment]
@astrofrog when you're trouble shooting this, I'd love to see how it's done, if you'd be OK with that. Thanks for looking into it...

**Comment by rsangole** [comment]
@astrofrog Any luck finding a solution to this? How can I help? (I use this tool for this purpose everyday, so I'm intrinsically motivated to solve this problem.)

**Comment by astrofrog** [comment]
Sorry for the delay! I'm mostly away from work until Monday, but what would be helpful is to know whether this is an issue with a change in glue, numpy, or pandas. Can you check whether downgrading pandas or numpy restores the original behavior?

**Comment by rsangole** [comment]
I spent an hour today playing around with the versions of pandas, numpy, glue-core and glueviz trying to recreate the dates correctly, but to no avail.  I have tried all combinations of the following versions, which all still result in the dates not being displayed correctly:

pandas - 0.19.2, 0.20.3, 0.21.1, 0.22.0
numpy - 1.11.3, 1.12.1, 1.13.3
glue-core - 0.11.0, 0.12.3
glueviz - 0.10.4, 0.11.0, 0.12.0, 0.12.2

I've tried doing some of this using conda and some using pip. But, nothing I've done gets me back to the dates being correctly shown as before.

Either I'm missing something, or there is another dependency for pandas/glue/numpy which isn't being downgraded.

Any ideas?

**Comment by rsangole** [comment]
Sorry to be pushy @astrofrog .... any chance you've had a moment to look into this? Thanks!

**Comment by astrofrog** [comment]
@rsangole - sorry for the delay, I've started looking into this, and I think what might have happened is that this data used to be converted to a string but is not converted to a number. A quick fix for now might be to force convert that data column to a string. I'll investigate a better solution tomorrow.

**Comment by rsangole** [comment]
@astrofrog Any luck, sir?
