### ISSUE TITLE
Hiding glue viewer axes and toolbars

### ISSUE THREAD

**Issue by drdavella** [glue-viz/glue#1495]
I have attempted to buy back more screen real estate in a particular plugin application by writing custom logic to hide the glue viewer axes and toolbars. This is done by manipulating the underlying mpl viewers directly.

My intent is to allow the axes and the toolbars to be toggled independently. However, I have noticed that first hiding the axes, and then hiding the toolbars, causes the axes to reappear. The axes will also reappear when resizing the main glue window.

The changes can be found here: https://github.com/spacetelescope/cubeviz/pull/150

**Comment by astrofrog** [comment]
I've explained how to do this here: https://github.com/spacetelescope/cubeviz/pull/150#issuecomment-357778723
