### ISSUE TITLE
Velocity shown in pixel coordinates in PV Slice View

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1602]
In the latest developer version, when a cut is made in p-v space, the velocity axis (and maybe also the position along cut axis) has units of pixels instead of units of meters per second. 

![pv_slice](https://user-images.githubusercontent.com/18339657/37302181-2c5a237c-2601-11e8-9eb6-c37d4f5dee96.png)

You'll see that the velocity axis has height 630 which is the length in pixels of the velocity axis of the cube.

**Comment by astrofrog** [comment]
@catherinezucker - which cube are you using? (I can't manage to reproduce this with the cubes I have)

**Comment by catherinezucker** [comment]
Hi Tom,

I am using the 12CO COMPLETE cube of Perseus ("PerA_12coFCRAO_F_vxy.fits.gz") which can be downloaded here:

https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:10904/10072

And here is my version info just in case!

Glue: 0.13.0.dev04425
Python: 3.6.3
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.2
PySide: Not installed
qtpy: 1.4.0
setuptools: 38.5.1
numpy: 1.13.3
matplotlib: 2.2.0
pandas: 0.22.0
astropy: 3.0.1
dill: 0.2.7.1
h5py: 2.7.1
xlrd: 1.1.0
mpl-scatter-density: 0.3
glue-core: 0.13.0.dev04425
glue-exp: unknown version
glue-vispy-viewers: 0.10.dev0
glue-wwt: unknown version
IPython: 6.2.1
qtconsole: 4.3.1
ipykernel: 4.8.2
traitlets: 4.3.2
pygments: 2.2.0
pyzmq: 17.0.0
scipy: 1.0.0
scikit-image: 0.13.1
PyAVM: Not installed
spectral-cube: 0.4.2
astrodendro: Not installed
mock: Not installed
pytest: 3.4.2
plotly: 2.4.1

Thanks!

**Comment by astrofrog** [comment]
@catherinezucker - I have a fix for this in #1615, which should be in the conda developer package later tomorrow. In the mean time, you can get around this by using the ``xyv`` cube instead of the ``vxy`` one. If you want to show the cube in RA/Dec and slice in velocity, the ``xyv`` cube should be a lot better performance-wise.

**Comment by catherinezucker** [comment]
Thanks so much for the speedy fix, @astrofrog ! That all sounds great, but I will switch over to the xyv for good measure.
