### ISSUE TITLE
Default to relative paths for session files

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1727]
We should default to relative paths instead of absolute paths for session files.

**Comment by astrofrog** [comment]
@chaityacshah - this would be a good issue to work on

**Comment by astrofrog** [comment]
@chaityacshah - I decided to go ahead and open a PR for this since it was requested again to me in the mean time. But I'll find some other issues you can work on!

The PR is here: https://github.com/glue-viz/glue/pull/1803

**Comment by chaityacshah** [comment]
@astrofrog Sure, Thank you!
