### ISSUE TITLE
Docs: Missing API docs?

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#1844]
I performed this search:
http://docs.glueviz.org/en/stable/search.html?q=keyboard&check_keywords=yes&area=default#

and clicked the top link:
http://glueviz.org/en/stable/api/glue.config.KeyboardShortcut.html?highlight=keyboard

and got a 404.  I haven't figured out how to build the docs locally to pin this issue down; where are the docs for building the docs?

**Comment by astrofrog** [comment]
@keflavich - the docs are just standard sphinx, so you can build locally by doing ``cd doc ; make html``

**Comment by astrofrog** [comment]
Huh interesting it's getting the domain wrong in the search results.

**Comment by astrofrog** [comment]
Ok I've fixed this, there were some old settings in RTD
