### ISSUE TITLE
Ipython terminal doesn't work when starting glue from qglue in jupyter notebook

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1872]
When you startup glue via a jupyter notebook, the ipython terminal is inactive and can't be accessed in the application. Here is a code example (courtesy of @janerigby):

```
Hack: Try to export these 2 dfs to Glue to visualize.  W/ C. Zucker
def passthrough(goesin):
    return(goesin)
from glue import qglue
#links = (['pmcat.JRRID'] , ['vdw.JRRID'], passthrough, passthrough)
app = qglue(pmcat=pmcat_jrr, vdw=vdw_all_jrr)#, links=[links])
---------------------------------------------------------------------------
AttributeError
                            Traceback (most recent call last)

/Applications/anaconda/lib/python2.7/site-packages/glue/app/qt/application.pyc in _toggle_terminal(self)
   1120         if self._terminal is None:
   1121             self._create_terminal()
-> 1122         if self._terminal.isVisible():
   1123             self._hide_terminal()
   1124             if self._terminal.isVisible():



AttributeError
: 'NoneType' object has no attribute 'isVisible'
```

This error exists in both the stable version (0.13.3) and the latest developer version.

**Comment by astrofrog** [comment]
This is expected due to the way IPython works. In principle this shouldn't matter too much because you should be able to use the IPython/notebook session you launched glue from instead?

**Comment by catherinezucker** [comment]
Thanks, Tom. You are right. I just need to add the %gui qt to my notebook so I can execute more cells ([here ](http://docs.glueviz.org/en/stable/python_guide/glue_from_python.html)for future posteriority). Closing this issue :).
