### ISSUE TITLE
Glue not working with matplotlib 2.0.2

### ISSUE THREAD

**Issue by entorm** [glue-viz/glue#1880]
Hello,
I just installed glue, and I think it's great. However, I found that some plotting keywords were not recognized in the 2D image plot on anaconda 3 with matplotlib 2.0.2 (I suspect that might be the case for other kinds of plots, that I haven't tried yet). I attach a .txt version of the changes in the data_viewer.py that I had to make in order to get it to work. I basically got rid of the problematic keywords, but someone more involved with the project will probably be able to fix this nicely in all the relevant files. 
Thanks for making this wonderful tool public!
Eva
[data_viewer.txt](https://github.com/glue-viz/glue/files/2488224/data_viewer.txt)

**Comment by astrofrog** [comment]
@entorm - what version of astropy do you have installed? I think this may be an astropy version issue (we now require astropy 2.x or later) rather than a matplotlib issue.

**Comment by astrofrog** [comment]
Great, thanks for confirming!
