### ISSUE TITLE
Any error in python console kills execution

### ISSUE THREAD

**Issue by aaronoppenheimer** [glue-viz/glue#1913]
If I force an error in the python console, it enters a state where it continues to run but will no longer execute anything. The only way to reset is to kill Glue - if I close and reopen the terminal, still the same.
```
In [1]: dc
Out[1]: 
DataCollection (0 data sets)
	

In [2]: xxx
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-38170c08cb45> in <module>
----> 1 xxx

NameError: name 'xxx' is not defined

In [3]: dc
ERROR: execution aborted
```

**Comment by astrofrog** [comment]
@aaronoppenheimer - that sounds like a bug - thanks for reporting! I'll investigate.

**Comment by hfs** [comment]
I have the same problem.

I have a fresh installation using pipenv. Here’s my version information in case it’s relevant:

Glue: 0.14.1
Python: 3.6.7
PyQt5: PyQt: 5.11.3 - Qt: 5.11.2
PySide2: Not installed
qtpy: 1.6.0
setuptools: 40.7.0
numpy: 1.16.0
bottleneck: 1.2.1
matplotlib: 3.0.2
pandas: 0.24.0
astropy: 3.1.1
dill: 0.2.9
h5py: 2.9.0
xlrd: 1.2.0
mpl-scatter-density: 0.5
glue-core: 0.14.1
glue-vispy-viewers: 0.11
IPython: 7.2.0
qtconsole: 4.4.3
ipykernel: 5.1.0
traitlets: 4.3.2
pygments: 2.3.1
pyzmq: 17.1.2
scipy: 1.2.0
scikit-image: Not installed
PyAVM: Not installed
spectral-cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: Not installed
plotly: Not installed

**Comment by astrofrog** [comment]
@hfs - thanks!

@aaronoppenheimer @hfs - what operating systems are you using?

**Comment by aaronoppenheimer** [comment]
Windows 10, with anaconda
  
  
  

  
  
  
  
  
>

**Comment by hfs** [comment]
I’m on Ubuntu Linux 18.04

**Comment by RRPJ** [comment]
Same issue with Linux Ubuntu 16.04. Was this resolved?

It makes the built-in terminal difficult to work with, as one typo or just trial and error results in a need to restart Glue.

**Comment by astrofrog** [comment]
It isn't resolved, and I'm investigating now. This used not to be an issue so I'm suspecting this could be due to an update in qtconsole.

**Comment by astrofrog** [comment]
This is a bug in ipykernel - the workaround for now is to downgrade to ipykernel <5, e.g. 4.10.0.

**Comment by astrofrog** [comment]
So for anyone using conda, try:

```
conda install ipykernel==4.10.0
```

or if using pip:

```
pip install ipykernel==4.10.0
```
