### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by candydad** [glue-viz/glue#1915]
install Glue in mac Mojave by pipenv ,after finished install,when run glue,I got the error ...

The Pipefile.lock(github do not support Pipefile.lock ,so I change the file name to Pipefile.loca.txt)

[Pipfile.lock.txt](https://github.com/glue-viz/glue/files/2729417/Pipfile.lock.txt)

**Comment by astrofrog** [comment]
@zhangqianghd - thanks for the report, I've run into this too, I'll investigate some more

**Comment by astrofrog** [comment]
@zhangqianghd - I've just release fast-histogram v0.6 (this was the culprit package). Could you try again?

**Comment by zhangqianghd** [comment]
OK,I will have a try as soon as possible.

**Comment by zhangqianghd** [comment]
I have update to v0.6,this time I can run Glue ,but I also get 'ModuleNotFoundError: No module named 'numpy.core._multiarray_umath''

Glue main window:
![glue_mainwindow](https://user-images.githubusercontent.com/1396270/50869556-83271980-13ef-11e9-8dd3-b9ca2f0de624.png)

Terminal message:
![glue_terminalinfo](https://user-images.githubusercontent.com/1396270/50869574-920dcc00-13ef-11e9-8627-8f71843e8db4.png)


The lastest Pipfile.lock
[Pipfile.lock.txt](https://github.com/glue-viz/glue/files/2738977/Pipfile.lock.txt)

**Comment by astrofrog** [comment]
@zhangqianghd - are there actually any issues when using glue despite that warning?

**Comment by astrofrog** [comment]
@zhangqianghd - can you try again? I've now released fast-histogram 0.7 which I think should fix things.

**Comment by astrofrog** [comment]
I'm going to close this as this should be addressed
