### ISSUE TITLE
Fonts color and definition issue 

### ISSUE THREAD

**Issue by ijpulidos** [glue-viz/glue#1921]
I installed glueviz using Anaconda distribution and I'm seeing the following font issue shown in the screenshot.

![image](https://user-images.githubusercontent.com/2949729/51545233-88448980-1e2f-11e9-80a5-631e8119709e.png)

I'm running it in Archlinux distribution with KDE (Plasma5) desktop environment and the version information from glueviz is in https://gist.github.com/ijpulidos/fc928b0b0ff4d76c1db2007883891493

I'm running glue from terminal with `glue -v` and it's showing some errors not sure if they are relevant, trace in https://gist.github.com/ijpulidos/f842947c84d11e00e303e59800f29f13

I have only seen this issue with Glueviz. Any ideas why this may be happening?

**Comment by astrofrog** [comment]
Thanks for the report and sorry about the issue! I'll investigate.

**Comment by ijpulidos** [comment]
Made some kind of progress but not idea why is this happening, due to the problem I then tried installing glueviz using AUR (which is an user repository for Archlinux, the package can be found here https://aur.archlinux.org/packages/glueviz/ ). This install of glue is working fine. The version_information from this glueviz install is in https://gist.github.com/ijpulidos/e1516bcf9f5effb97fb3183601664d46

**Comment by ijpulidos** [comment]
On other news, the anaconda navigator seems to be having the same issue, this may be then an issue with Anaconda and not glueviz. You can see how in the previous message the Qt versions are different, maybe something there?

**Comment by ijpulidos** [comment]
Ok, for what is worth, this is a problem I've been facing with many apps and I finally did something that made it work. I just had to use `RGB` as subpixel rendering option in my fonts hinting options.

![image](https://user-images.githubusercontent.com/2949729/56305841-a3f5be00-6106-11e9-8674-cfd37451562f.png)

This wasn't a gueviz problem but I consider it resolved.
