### ISSUE TITLE
Error message when installing Glueviz using Ananconda on Windows

### ISSUE THREAD

**Issue by dsmasinde** [glue-viz/glue#1947]
Hello there

I have tried installing Glueviz using Anaconda but errors are showing everytime:
The commands are:
1   "conda update -n root conda" 
2  "conda install -c glueviz glueviz=0.14"

I will be grateful if anyone could advise me on the way foward.
I have attached a screen shot of the error message here in .JPEG.
Thanking you in advance.

![error](https://user-images.githubusercontent.com/11613210/53798054-8a2e5c00-3f48-11e9-8b6e-68db7ac2ccc0.JPG)

**Comment by astrofrog** [comment]
Can you try just the second command? I wonder if you do not have sufficient permissions to update conda in the root environment.

**Comment by dsmasinde** [comment]
I have admin rights but it just cant install Glueviz and others
David S. Masinde

**Comment by astrofrog** [comment]
This looks like a generic conda issue and I'm not sure how to solve it. Could you maybe try using glueconda:

http://docs.glueviz.org/en/stable/installation/glueconda.html

which is a self-contained conda installation with glue?

**Comment by astrofrog** [comment]
I'm going to close this since it isn't a glue-specific issue.
