### ISSUE TITLE
Missing programs in Anaconda Navigator

### ISSUE THREAD

**Issue by dsmasinde** [glue-viz/glue#1948]
Dear friends

I have not understood why some programs like RStudio, VS Code, Glueviz and Orange 3 are not all installed when you make the first installation of the Ananconda Navigator.

Any advise?

**Comment by astrofrog** [comment]
@dsmasinde the navigator shows which programs are available to install but not all are installed by default since not all users necessarily want it. If you think this is confusing at the moment, I would suggest opening an issue in https://github.com/ContinuumIO/anaconda-issues
