### ISSUE TITLE
Error bars with sudden color scale issue

### ISSUE THREAD

**Issue by RRPJ** [glue-viz/glue#1950]
Hi!

I'm an astronomy student working on some datafile. The issue I'm having here is that when plotting error bars in a 2d scatter plot, the error bars get a specific color when you assigned a color scheme to one of the parameters of the 2d scatter plot. It _seems_ unrelated to the value of the datapoint, but I can't seem to find a pattern or reason for Glue doing so.

Attached are picture 1, without error bars, with a color scaling to the x-axis, as is easily seen.
Picture 2 then shows the same plot with error bars, with colors appearing quite randomly, but it is always the same (hence my efforts to find a pattern). 

There is no option in Glue for these colors in error bars as far as I can see. 
Does someone know what is going on here?

Cheers!

Rutger

![gh1](https://user-images.githubusercontent.com/45002288/53883495-6edf5180-4019-11e9-944c-592dad6a9f2f.png)

![gh2](https://user-images.githubusercontent.com/45002288/53883506-7272d880-4019-11e9-9780-789979f08ee3.png)

**Comment by astrofrog** [comment]
@RRPJ - the color of the error bars should match the color of the points, so it looks like there may be a bug here if the only thing you are changing is turning error bars on/off. I'll investigate!

**Comment by astrofrog** [comment]
@RRPJ - what version of glue are you using? You can find out via Help -> Version information (if you can just copy all the info there that would be great)

**Comment by RRPJ** [comment]
There you go!

Glue: 0.14.2
Python: 3.7.1
PyQt5: PyQt: 5.9.2 - Qt: 5.9.6
PySide2: Not installed
qtpy: 1.5.2
setuptools: 40.6.3
numpy: 1.15.4
bottleneck: 1.2.1
matplotlib: 3.0.2
pandas: 0.23.4
astropy: 3.1
dill: 0.2.8.2
h5py: 2.8.0
xlrd: 1.2.0
mpl-scatter-density: 0.5
glue-core: 0.14.2
glue-vispy-viewers: 0.11
IPython: 7.2.0
qtconsole: 4.4.3
ipykernel: 5.1.0
traitlets: 4.3.2
pygments: 2.3.1
pyzmq: 17.1.2
scipy: 1.1.0
scikit-image: 0.14.1
PyAVM: Not installed
spectral-cube: 0.4.4
astrodendro: Not installed
mock: Not installed
pytest: 4.0.2
plotly: 3.6.1

**Comment by astrofrog** [comment]
This is due to a bug in Matplotlib: https://github.com/matplotlib/matplotlib/issues/13799 - I'll try and think of whether we can work around this here.
