### ISSUE TITLE
Default "Spectral" Axis in Spectral Tool

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1957]
If you display GLON vs. GLAT in the 2D image viewer, and click on the spectral tool in that window, the "spectral" axis will default to velocity (as it should). However, if you have GLON vs. VEL displayed, and click on the spectral tool, it will display the velocity axis as the spectral axis by default (instead of latitude) so it will make it seem like the spectral tool is broken because it is not responding as the user navigates through the velocity channels (and the user doesn't notice it defaults to velocity). So the default should be (I think) to make the "spectral" axis be whatever the third axis not displayed is, instead of always defaulting to velocity (that will confuse people less, I think!).

**Comment by astrofrog** [comment]
I agree - I actually started working on this already in https://github.com/glue-viz/glue/pull/1881 and will try and finish it up soon :)

**Comment by astrofrog** [comment]
@catherinezucker - this should now be fixed in the latest developer version of glue-core, can you try updating?

**Comment by astrofrog** [comment]
I'm going to close this since it should be fixed
