### ISSUE TITLE
Installing on PC with FireWall-Blocked Internet Connection

### ISSUE THREAD

**Issue by RobertoGO** [glue-viz/glue#2063]
Hi,
I would like to install GlueViz on my PC, but the Anaconda install option and the PIP install option do not work for me because some urls that need to be accessed are blocked by a firewall.

Is it possible to download the source code to another non-blocked PC, copy it and install it in my blocked PC? If so, could you tell me how? I have not found anything for this here:
https://glueviz.readthedocs.io/en/stable/installation/installation.html

Thanks very much in advance.

**Comment by astrofrog** [comment]
@RobertoGO - one solution is to use the 'glueconda' distribution which you can find out about here:

http://docs.glueviz.org/en/latest/installation/glueconda.html

this is a self-contained conda installation with glue and all dependencies already installed. Could you let me know if that works?
