### ISSUE TITLE
If top bar is hidden it can not be recovered

### ISSUE THREAD

**Issue by Gabriel-p** [glue-viz/glue#2069]
Example:

![Captura de pantalla de 2019-10-10 11-17-12](https://user-images.githubusercontent.com/6054951/66577331-92d6b880-eb4f-11e9-920f-b7df39d0e244.png)

The top bar of the plot window is hidden and there is no way (?) to recover it. I can not move or close that window.

**Comment by astrofrog** [comment]
@Gabriel-p - do you see any scrollbars on the right or bottom of the main window? When there are enough viewers, the canvas becomes larger than the screen and you need to scroll to see the top of the sub-windows.

**Comment by Gabriel-p** [comment]
Sorry, can't reproduce this anymore. Closing.
