### ISSUE TITLE
Compatibility with Matplotlib 3.1.3

### ISSUE THREAD

**Issue by specmicp** [glue-viz/glue#2091]
(Continuation of the discussion in https://github.com/glue-viz/glue/pull/2090, because it is unrelated)

Tests in glue/viewers/image/qt/tests/test_data_viewer.py are failing:

- test_slice_change_single_draw
- test_update_subset_ignored_if_not_present

(example of failed tests: https://dev.azure.com/glue-viz/glue/_build/results?buildId=487&view=logs&jobId=e31e1c80-7337-58fc-f10c-7ed77e80e102&j=e31e1c80-7337-58fc-f10c-7ed77e80e102&t=df35b83d-b4d5-50fc-c648-b1233c5c329f )

Fails only occur with Matplotlib 3.1.3 but not with Matplotlib 3.1.2

with matplotlib 3.1.3: this version of the test is not working:

```python
    def test_update_subset_ignored_if_not_present(self):
        # This can be quite a difficult test to pass because it makes sure that
        # there are absolutely no references to the layer state left over once
        # a subset is removed - when originally written this identified quite
        # a few places where references were being accidentally kept, and
        # resulted in weakref being needed in a number of places. But ultimately
        # this test should pass! No cheating :)
        self.init_draw_count()
        self.data_collection.append(self.data)
        self.viewer.add_data(self.data)
        sub = self.data.new_subset()
        #print(self.draw_count)
        self.viewer.remove_subset(sub)
        ct0 = self.draw_count
        assert self.draw_count == ct0
```

However, this version is passing (only difference is the print(self.draw_count):
```python
    def test_update_subset_ignored_if_not_present(self):
        # This can be quite a difficult test to pass because it makes sure that
        # there are absolutely no references to the layer state left over once
        # a subset is removed - when originally written this identified quite
        # a few places where references were being accidentally kept, and
        # resulted in weakref being needed in a number of places. But ultimately
        # this test should pass! No cheating :)
        self.init_draw_count()
        self.data_collection.append(self.data)
        self.viewer.add_data(self.data)
        sub = self.data.new_subset()
        print(self.draw_count)
        self.viewer.remove_subset(sub)
        ct0 = self.draw_count
        assert self.draw_count == ct0
```

it seems that it is unrelated to what the test is really testing, and more due to a delayed drawing/processing of the events...

This is the changelog of matplotlib 3.1.3: https://matplotlib.org/3.1.3/users/whats_new.html

These are the commits between 3.1.2 and 3.1.3: https://github.com/matplotlib/matplotlib/compare/v3.1.2...v3.1.3

One of the maybe relevant commit changing the behavior of draw_idle is : https://github.com/matplotlib/matplotlib/commit/12004eda6ab4192511f5f6727980e106038fdde5

I do not understand in details the internal of matplotlib, so I'm not sure how to continue this investigation, but I hope this information helps.

**Comment by astrofrog** [comment]
This is very helpful, thanks! Investigating further

**Comment by astrofrog** [comment]
I've fixed all the CI issues in https://github.com/glue-viz/glue/pull/2098 - thanks, this was very helpful!
