### ISSUE TITLE
in-place patch for session in user config files

### ISSUE THREAD

**Issue by specmicp** [glue-viz/glue#2120]
During development of the glue software, or of plugins for glue some attributes are added/removed or have their name, or type changed. The unfortunate side effect is that session files created from a previous version do not open anymore.
It is sometimes possible to edit the session files, but the size of that file makes it difficult, especially if many sessions files was created.

Another approach is to add a piece of code changing the bad part of the session file such that the session file can be open.
It is currently possible in the current code, by adding that piece of code in the function: glue.core.state.apply_inplace_patches.
This seems however a generally bad idea, especially for plugins development

The solution I'd like is the ability to provide to glue a path to a folder containing python-patch file.
These patches would be applied to the session files when it is opened.
The plugin developper would then be in charge of distributing the correct patches for its plugins.

The pros:
- we don't have to restart that precious analyses urgently needed to finish that most important paper just because we updated a plugin...
- The core development is even more separated from the plugins development, each plugin dev can provide the correct patches necessary for its plugins

The cons:
- It might make it too easy to break compatibility
- Compatibility problems between the different plugins might be possible
- Old patches might accumulate and create more problems in the future

Example of use:
Before 1.15, Glue did not provide the glue.core.coordinates.AffineCoordinates class. In my plugin I add a class providing similar abilities. I changed my code to now use the Glue class, but I need to support both classes now, or break compatibility.
This addition would allow me to replace one class by another in the session file without repercussion for the user.

**Comment by astrofrog** [comment]
I really like this idea, and maybe the patches could be kept in a registry - plugins are loaded and registries are populated before session files are opened, so that could work? So this could take the form:

```
@session_patch
def patch_session_geospatial(session_object):
    ...
```
