### ISSUE TITLE
Legend and background color

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#2145]
Viewers can have a custom background/foreground color (which can be changed in the preferences), for example white on black instead of black on white. We might want to consider making the legend follow this so that the background and text color match the rest of the figure:

![Screenshot from 2020-05-20 15-01-34](https://user-images.githubusercontent.com/314716/82455423-d6f94680-9aaa-11ea-8c53-66f3c908a278.png)

cc @specmicp

**Comment by astrofrog** [comment]
I'm not actually 100% sure we want to always match these - maybe we could even allow the user to customize the color of text/background in the legend. @specmicp what do you think?

**Comment by specmicp** [comment]
It's should be possible to change the frame color and the font color of the legend. The default values could be filled using the custom background/foreground color to have a match by default. It should be relatively easy, I'll start working on it.

Is this foreground/background color also exported in the plot scripts ? I don't remember having seen anything about this.
