### ISSUE TITLE
attempting 2D scatter results in AttributeError: 'NoneType' object has no attribute 'vmin'

### ISSUE THREAD

**Issue by webradio** [glue-viz/glue#2165]
**Describe the bug**
A new data viewer with 2D scatter displays error message "Failed to add data. 'NoneType' object has no attribute 'vmin'"

**To Reproduce**
Run the following python script. I use Visual Studio Code.

    import numpy as np
    import pandas as pd
    from glue import qglue
    df = pd.DataFrame({'x':[1,2], 'y':[3,4]})
    app = qglue(df=df.reset_index())

In Glue, choose Canvas -> New Data Viewer, 2D scatter, click ok.

**Expected behavior**
A new data viewer window opens.

**Screenshots**
[Screenshot of error message](https://i.imgur.com/gE5ZcjI.png)

**Details:**

- Operating System: Ubuntu 18.04.4 LTS
- Python version (``python --version``): Python 3.7.8
- Glue version (``glue --version``): 0.15.6
- How you installed glue: conda

Traceback

    Traceback (most recent call last):
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/utils/qt/decorators.py", line 63, in decorated
        return f(*args, **kwargs)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/viewers/common/qt/data_viewer.py", line 220, in add_data
        return super(DataViewer, self).add_data(data)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/viewers/common/viewer.py", line 200, in add_data
        layer = get_layer_artist_from_registry(data, self) or self.get_data_layer_artist(data)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/utils/matplotlib.py", line 165, in wrapper
        return func(*args, **kwargs)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/utils/matplotlib.py", line 165, in wrapper
        return func(*args, **kwargs)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/viewers/common/viewer.py", line 225, in get_data_layer_artist
        return self.get_layer_artist(self._data_artist_cls, layer=layer, layer_state=layer_state)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/utils/matplotlib.py", line 165, in wrapper
        return func(*args, **kwargs)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/utils/matplotlib.py", line 165, in wrapper
        return func(*args, **kwargs)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/viewers/matplotlib/viewer.py", line 214, in get_layer_artist
        return cls(self.axes, self.state, layer=layer, layer_state=layer_state)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/glue/viewers/scatter/layer_artist.py", line 160, in __init__
        histogram2d_func=self.compute_density_map)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/mpl_scatter_density/generic_density_artist.py", line 56, in __init__
        super(GenericDensityArtist, self).__init__(ax, array_func=histogram2d_func, dpi=dpi, update_while_panning=update_while_panning, **kwargs)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/mpl_scatter_density/base_image_artist.py", line 56, in __init__
        super(BaseImageArtist, self).__init__(ax, **kwargs)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/matplotlib/image.py", line 906, in __init__
        **kwargs
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/matplotlib/image.py", line 244, in __init__
        cm.ScalarMappable.__init__(self, norm, cmap)
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/matplotlib/cm.py", line 234, in __init__
        self.set_norm(norm)  # The Normalize instance of this ScalarMappable.
      File "/home/user/miniconda3/envs/iapws/lib/python3.7/site-packages/mpl_scatter_density/generic_density_artist.py", line 91, in set_norm
        if norm.vmin is not None:
    AttributeError: 'NoneType' object has no attribute 'vmin'

Packages

    # packages in environment at /home/user/miniconda3/envs/iapws:
    #
    # Name                    Version                   Build  Channel
    _libgcc_mutex             0.1                 conda_forge    conda-forge
    _openmp_mutex             4.5                       0_gnu    conda-forge
    astroid                   2.4.2            py37hc8dfbb8_0    conda-forge
    astropy                   4.0.1.post1      py37h8f50634_0    conda-forge
    attrs                     19.3.0                     py_0    conda-forge
    backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
    backports                 1.0                        py_2    conda-forge
    backports.functools_lru_cache 1.6.1                      py_0    conda-forge
    bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
    blosc                     1.20.0               he1b5a44_0    conda-forge
    bokeh                     2.1.1            py37hc8dfbb8_0    conda-forge
    bottleneck                1.3.2            py37h03ebfcd_1    conda-forge
    brotli                    1.0.7             he1b5a44_1004    conda-forge
    brunsli                   0.1                  he1b5a44_0    conda-forge
    bzip2                     1.0.8                h516909a_2    conda-forge
    ca-certificates           2020.6.20            hecda079_0    conda-forge
    certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
    charls                    2.1.0                he1b5a44_2    conda-forge
    click                     7.1.2              pyh9f0ad1d_0    conda-forge
    cloudpickle               1.5.0                      py_0    conda-forge
    cycler                    0.10.0                     py_2    conda-forge
    cytoolz                   0.10.1           py37h516909a_0    conda-forge
    dask                      2.21.0                     py_0    conda-forge
    dask-core                 2.21.0                     py_0    conda-forge
    dbus                      1.13.6               he372182_0    conda-forge
    decorator                 4.4.2                      py_0    conda-forge
    defusedxml                0.6.0                      py_0    conda-forge
    dill                      0.3.2              pyh9f0ad1d_0    conda-forge
    distributed               2.21.0           py37hc8dfbb8_0    conda-forge
    entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
    expat                     2.2.9                he1b5a44_2    conda-forge
    fast-histogram            0.7             py37hc1659b7_1000    conda-forge
    fastcache                 1.1.0            py37h8f50634_1    conda-forge
    fluids                    0.1.83             pyh9f0ad1d_0    conda-forge
    fontconfig                2.13.1            h86ecdb6_1001    conda-forge
    freetype                  2.10.2               he06d7ca_0    conda-forge
    fsspec                    0.7.4                      py_0    conda-forge
    fuzzywuzzy                0.17.0                     py_0    conda-forge
    gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
    giflib                    5.2.1                h516909a_2    conda-forge
    glib                      2.65.0               h6f030ca_0    conda-forge
    glue-core                 0.15.6                   py37_1    conda-forge
    glue-vispy-viewers        0.12.2                     py_0    conda-forge
    glueviz                   0.15.2                        0    conda-forge
    gmp                       6.2.0                he1b5a44_2    conda-forge
    gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
    gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
    gstreamer                 1.14.5               h36ae1b5_2    conda-forge
    h5py                      2.10.0          nompi_py37h90cd8ad_104    conda-forge
    hdf5                      1.10.6          nompi_h3c11f04_100    conda-forge
    heapdict                  1.0.1                      py_0    conda-forge
    iapws                     1.5.2              pyh9f0ad1d_0    conda-forge
    icu                       64.2                 he1b5a44_1    conda-forge
    imagecodecs               2020.5.30        py37hda6ee5b_2    conda-forge
    imageio                   2.9.0                      py_0    conda-forge
    importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
    importlib_metadata        1.7.0                         0    conda-forge
    ipykernel                 5.3.4            py37h43977f1_0    conda-forge
    ipython                   7.16.1           py37h43977f1_0    conda-forge
    ipython_genutils          0.2.0                      py_1    conda-forge
    ipywidgets                7.5.1                      py_0    conda-forge
    isort                     4.3.21           py37hc8dfbb8_1    conda-forge
    jedi                      0.17.2           py37hc8dfbb8_0    conda-forge
    jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
    jpeg                      9d                   h516909a_0    conda-forge
    jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
    jupyter                   1.0.0                      py_2    conda-forge
    jupyter_client            6.1.6                      py_0    conda-forge
    jupyter_console           6.1.0                      py_1    conda-forge
    jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
    jxrlib                    1.1                  h516909a_2    conda-forge
    kiwisolver                1.2.0            py37h99015e2_0    conda-forge
    lazy-object-proxy         1.4.3            py37h8f50634_2    conda-forge
    lcms2                     2.11                 hbd6801e_0    conda-forge
    ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
    lerc                      2.2                  he1b5a44_0    conda-forge
    libaec                    1.0.4                he1b5a44_1    conda-forge
    libblas                   3.8.0               17_openblas    conda-forge
    libcblas                  3.8.0               17_openblas    conda-forge
    libclang                  9.0.1           default_hde54327_0    conda-forge
    libffi                    3.2.1             he1b5a44_1007    conda-forge
    libgcc-ng                 9.3.0               h24d8f2e_11    conda-forge
    libgfortran-ng            7.5.0               hdf63c60_11    conda-forge
    libgomp                   9.3.0               h24d8f2e_11    conda-forge
    libiconv                  1.15              h516909a_1006    conda-forge
    liblapack                 3.8.0               17_openblas    conda-forge
    libllvm9                  9.0.1                he513fc3_1    conda-forge
    libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
    libpng                    1.6.37               hed695b0_1    conda-forge
    libsodium                 1.0.17               h516909a_0    conda-forge
    libstdcxx-ng              9.3.0               hdf63c60_11    conda-forge
    libtiff                   4.1.0                hc7e4089_6    conda-forge
    libuuid                   2.32.1            h14c3975_1000    conda-forge
    libwebp-base              1.1.0                h516909a_3    conda-forge
    libxcb                    1.13              h14c3975_1002    conda-forge
    libxkbcommon              0.10.0               he1b5a44_0    conda-forge
    libxml2                   2.9.10               hee79883_0    conda-forge
    libzopfli                 1.0.3                he1b5a44_0    conda-forge
    locket                    0.2.0                      py_2    conda-forge
    lz4-c                     1.9.2                he1b5a44_1    conda-forge
    markupsafe                1.1.1            py37h8f50634_1    conda-forge
    matplotlib                3.3.0                         1    conda-forge
    matplotlib-base           3.3.0            py37hd478181_1    conda-forge
    mccabe                    0.6.1                      py_1    conda-forge
    mistune                   0.8.4           py37h8f50634_1001    conda-forge
    mpc                       1.1.0             h04dde30_1007    conda-forge
    mpfr                      4.0.2                he80fd80_1    conda-forge
    mpl-scatter-density       0.6                        py_1    conda-forge
    mpmath                    1.1.0                      py_0    conda-forge
    msgpack-python            1.0.0            py37h99015e2_1    conda-forge
    nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
    nbformat                  5.0.7                      py_0    conda-forge
    ncurses                   6.2                  he1b5a44_1    conda-forge
    networkx                  2.4                        py_1    conda-forge
    notebook                  6.0.3            py37hc8dfbb8_1    conda-forge
    nspr                      4.27                 he1b5a44_0    conda-forge
    nss                       3.47                 he751ad9_0    conda-forge
    numpy                     1.19.1           py37h8960a57_0    conda-forge
    olefile                   0.46                       py_0    conda-forge
    openjpeg                  2.3.1                h981e76c_3    conda-forge
    openssl                   1.1.1g               h516909a_1    conda-forge
    packaging                 20.4               pyh9f0ad1d_0    conda-forge
    pandas                    1.1.0            py37h3340039_0    conda-forge
    pandoc                    2.10.1               h516909a_0    conda-forge
    pandocfilters             1.4.2                      py_1    conda-forge
    parso                     0.7.1              pyh9f0ad1d_0    conda-forge
    partd                     1.1.0                      py_0    conda-forge
    pcre                      8.44                 he1b5a44_0    conda-forge
    pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
    pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
    pillow                    7.2.0            py37h718be6c_1    conda-forge
    pint                      0.14                       py_0    conda-forge
    pip                       20.2                       py_0    conda-forge
    prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
    prompt-toolkit            3.0.5                      py_1    conda-forge
    prompt_toolkit            3.0.5                         1    conda-forge
    psutil                    5.7.2            py37h8f50634_0    conda-forge
    pthread-stubs             0.4               h14c3975_1001    conda-forge
    ptyprocess                0.6.0                   py_1001    conda-forge
    pygments                  2.6.1                      py_0    conda-forge
    pylint                    2.5.3            py37hc8dfbb8_0    conda-forge
    pyopengl                  3.1.5                      py_0    conda-forge
    pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
    pyqt                      5.12.3           py37h8685d9f_3    conda-forge
    pyqt5-sip                 4.19.18                  pypi_0    pypi
    pyqtchart                 5.12                     pypi_0    pypi
    pyqtwebengine             5.12.1                   pypi_0    pypi
    pyrsistent                0.16.0           py37h8f50634_0    conda-forge
    python                    3.7.8           h6f2ec95_1_cpython    conda-forge
    python-dateutil           2.8.1                      py_0    conda-forge
    python-levenshtein        0.12.0          py37h516909a_1001    conda-forge
    python_abi                3.7                     1_cp37m    conda-forge
    pytz                      2020.1             pyh9f0ad1d_0    conda-forge
    pywavelets                1.1.1            py37h03ebfcd_1    conda-forge
    pyyaml                    5.3.1            py37h8f50634_0    conda-forge
    pyzmq                     19.0.1           py37hac76be4_0    conda-forge
    qt                        5.12.5               hd8c4c69_1    conda-forge
    qtconsole                 4.7.5              pyh9f0ad1d_0    conda-forge
    qtpy                      1.9.0                      py_0    conda-forge
    readline                  8.0                  he28a2e2_2    conda-forge
    scikit-image              0.17.2           py37h0da4684_1    conda-forge
    scipy                     1.5.2            py37hb14ef9d_0    conda-forge
    send2trash                1.5.0                      py_0    conda-forge
    setuptools                49.2.0           py37hc8dfbb8_0    conda-forge
    six                       1.15.0             pyh9f0ad1d_0    conda-forge
    snappy                    1.1.8                he1b5a44_3    conda-forge
    sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
    sqlite                    3.32.3               hcee41ef_1    conda-forge
    sympy                     1.6.1            py37hc8dfbb8_0    conda-forge
    tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
    tblib                     1.6.0                      py_0    conda-forge
    terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
    testpath                  0.4.4                      py_0    conda-forge
    tifffile                  2020.7.24                  py_0    conda-forge
    tk                        8.6.10               hed695b0_0    conda-forge
    toml                      0.10.1             pyh9f0ad1d_0    conda-forge
    toolz                     0.10.0                     py_0    conda-forge
    tornado                   6.0.4            py37h8f50634_1    conda-forge
    traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
    typed-ast                 1.4.1            py37h516909a_0    conda-forge
    typing_extensions         3.7.4.2                    py_0    conda-forge
    wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
    webencodings              0.5.1                      py_1    conda-forge
    wheel                     0.34.2                     py_1    conda-forge
    widgetsnbextension        3.5.1            py37hc8dfbb8_1    conda-forge
    wrapt                     1.11.2           py37h8f50634_0    conda-forge
    xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
    xorg-libxau               1.0.9                h14c3975_0    conda-forge
    xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
    xz                        5.2.5                h516909a_1    conda-forge
    yaml                      0.2.5                h516909a_0    conda-forge
    zeromq                    4.3.2                he1b5a44_2    conda-forge
    zfp                       0.5.5                he1b5a44_1    conda-forge
    zict                      2.0.0                      py_0    conda-forge
    zipp                      3.1.0                      py_0    conda-forge
    zlib                      1.2.11            h516909a_1006    conda-forge
    zstd                      1.4.5                h6597ccf_2    conda-forge

**Additional context**
`conda update --all` the evening before.

**Comment by astrofrog** [comment]
Thanks for the report! This will be fixed once the conda package for mpl-scatter-density v0.7 is available

**Comment by astrofrog** [comment]
@webradio - could you try again? I think this should be fixed now that mpl-scatter-density v0.7 is available on conda

**Comment by webradio** [comment]
Indeed, I got now mpl-scatter-density 0.7 (reinstalled miniconda today and re-created the environment) and the error is gone. Thank you for a quick check and apologizes for a delayed feedback.
