### ISSUE TITLE
Support for Voila 0.2

### ISSUE THREAD

**Issue by mariobuikhuizen** [glue-viz/glue#2174]
Voila 0.2 has a dependency on jupyter_client>=6.1.3. Glue-core has a dependency on jupyter-client <6 introduced in https://github.com/glue-viz/glue/commit/8a8d5fdf869493d42f99ce976823b3f5434e8b99

Is this dependency still necessary?

**Comment by astrofrog** [comment]
I don't think the pinning should be needed anymore. Want to open a PR to remove this? :)

**Comment by mariobuikhuizen** [comment]
sure!
