### ISSUE TITLE
Documentation on converting data objects is out-of-date

### ISSUE THREAD

**Issue by jfoster17** [glue-viz/glue#2211]
**Describe the bug**
[Documentation on converting data objects](http://docs.glueviz.org/en/stable/python_guide/data_translation.html#converting-data-objects) is out-of-date

**To Reproduce**
Follow the commands shown on [documentation page](http://docs.glueviz.org/en/stable/python_guide/data_translation.html#converting-data-objects):
```
from pandas import DataFrame
df1 = DataFrame()
df1['a'] = [1.2, 3.4, 2.9]
df1['g'] = ['r', 'q', 's']
from glue.core import DataCollection
dc = DataCollection()
dc['dataframe'] = df1

```
get

`TypeError: 'DataCollection' object does not support item assignment
`

**Expected behavior**
Documentation says this assigns the dataframe to the DataCollection object

**Details:**

- Operating System: MacOS 10.14.6
- Python version: python 3.7.7
- Glue version: 1.0.0 
- How you installed glue: conda

**Comment by astrofrog** [comment]
Huh curious, this is actually a new feature that should be in recent glue versions!

**Comment by jfoster17** [comment]
Yeah, I think it was something odd with my environment. I *thought* I was able to reproduce it in a clean new environment, but actually I am not. Closing...
