### ISSUE TITLE
Installation fails on Python 3.10 + MacOS

### ISSUE THREAD

**Issue by neutrinoceros** [glue-viz/glue#2257]
**Describe the bug**

I'm surprised that I didn't find any similar issue in the tracker, apologies if I just didn't look close enough

Right now glueviz fails to build on my machine with MacOS 12.0.1 (Monterey) and Python 3.10.0
```
pip install glueviz
```

As far as I understand, the real problem is with bottleneck (a build time dependency to glue) not being maintained, with many build-related issues in their tracker
https://github.com/pydata/bottleneck/issues

I wonder if there's anything that can be done on glueviz' side to mitigate this problem, like making bottleneck an optional dependency (maybe just for Python 3.10 and above) ? 

**Details:**

- Operating System: MacOS 12.0.1
- Python version (``python --version``): Python 3.10.0
- Glue version (``glue --version``): None
- How you installed glue: couldn't

**Additional context**

**Comment by astrofrog** [comment]
@neutrinoceros - could you try and ``pip install glue-core==1.2.3`` to see if that fixes it? (I just released it today). I've removed the bottleneck dependency.

**Comment by neutrinoceros** [comment]
I confirm that the new release fixed the problem, thank you !
