### ISSUE TITLE
Please release glue-core

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#2301]
@orifox really wants a new release with #2298 in it. cc @rosteen 

[🐱](https://jira.stsci.edu/browse/JDAT-2464)

**Comment by dhomeier** [comment]
@astrofrog would this be a similar process to glue-jupyter? Should we try to merge #2299, #2300, #2302 for 1.3.1 as well?

**Comment by astrofrog** [comment]
@dhomeier - I think the process is the same, I've just pushed v1.4.0 to make sure it all works fine and if so you can always do some of the future releases?

**Comment by dhomeier** [comment]
Closed by #2302/578369f or shall we leave this open as a permanent ticket? 😁

**Comment by pllim** [comment]
Thanks for all the fixes and releases!
