### ISSUE TITLE
pvextractor should not be in install_requires

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#2316]
https://github.com/glue-viz/glue/blob/f8c1e9646e7252aa13f5f58c4838cb9b670875d3/setup.cfg#L46

https://github.com/radio-astro-tools/pvextractor/blob/9911f297a7978c8afb3fe6f6d937d6b03161031c/setup.cfg#L24 (it pulls in spectral-cube)

Blocks https://github.com/glue-viz/glue-astronomy/pull/76

**Comment by astrofrog** [comment]
We do rely on it for some core functionality for now. However I do have a work in progress branch to remove it as we will be doing slicing along paths In a different way.

@pllim why all the spectral-cube dislike?

**Comment by pllim** [comment]
Not particularly targeting on that package. We just want to minimize installing unused packages downstream and that was the one thing we're sure we don't need. Jdaviz is deployed on MAST and so on.
