### ISSUE TITLE
Please test downstream packages before releasing

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#2383]
This is in regards to https://github.com/glue-viz/glue/commit/da68d1a63adfd6f91aac1e7d2cf864a359c33baa#r107847297 (https://github.com/glue-viz/glue/pull/2344) that got merged last minute before glue-core v1.9 was released. As a result, Jdaviz never had a chance to catch that it broke our stuff downstream even though we have CI job to test against glue dev stack.

Now we are unable to take advantage of another feature that was in the same release (#2379) for unit conversion work downstream.

In the future, please give downstream a chance to catch problems before a stable release.

xref https://github.com/glue-viz/glue-jupyter/pull/349 and https://github.com/spacetelescope/jdaviz/pull/2135

**Comment by astrofrog** [comment]
I've now set up an integration testing repo to help us check whether we can go ahead with releases without breaking downstream: https://github.com/glue-viz/glue-integration-testing
