### ISSUE TITLE
"Fill markers" button doesn't work in "Writing a custom viewer for glue with Qt" tutorial

### ISSUE THREAD

**Issue by sergiopasra** [glue-viz/glue#2388]
**Describe the bug**
I'm following the "Writing a custom viewer for glue with Qt" tutorial. I have copied the `TutorialViewer` classes and `viewer_state.ui`. I load a csv file and I mostly obtain what is expected with one exception. The "Fill markers" toggle button does nothing. The `fill` property is never updated and the method `_on_fill_change`is never called.

If I add a callback to `self.checkbox`, than I can get the desired behavior, but `connect_checkable_button` is not working correctly.

**To Reproduce**
Steps to reproduce the behavior such as:
1. Copy the code in "Writing a custom viewer for glue with Qt" 
2. Load a CSV file
3. Drag to plot
4. Select "Tutorial Viewer"
5. Click on "Fill markers"

**Expected behavior**
Markers on the plot are filled.

**Details:**

- Operating System: Linux Fedora 37 
- Python version: Python 3.11.2, Python 3.10.10
- Glue version: 1.9.2.dev1+g4717aa72
- How you installed glue:  pip

**Comment by sergiopasra** [comment]
Thank you! Now code like this makes more sense:

```
self._connections = autoconnect_callbacks_to_qt(self.viewer_state, self.ui)
```

So the value returned by `autoconnect_callbacks_to_qt` is retained.

How do I store more than one callback? Looks like `autoconnect_callbacks_to_qt` returns a dictionary.

**Comment by Carifio24** [comment]
It shouldn't really matter how they're stored - you could have a member value (of the `TutorialLayerStateWidget`) that's a list of connections, or a dictionary with the connections as values (like `autoconnect_callbacks_to_qt`), or just have each connection as a separate member value. As long as the connection is still retained somewhere, the callback setup will work correctly.

If you end up having a decent number of connections, note that you could also use the same pattern for the layer state as for the viewer state - create a `.ui` file that follows echo's autoconnect [naming conventions](https://echo.readthedocs.io/en/latest/api/echo.qt.autoconnect_callbacks_to_qt.html#echo.qt.autoconnect_callbacks_to_qt) and call `autoconnect_callbacks_to_qt` to create the connections for you.
