### ISSUE TITLE
compute_fixed_resolution_buffer fails with some components powered by dask arrays

### ISSUE THREAD

**Issue by jfoster17** [glue-viz/glue#2397]
**Describe the bug**
In a real-world example (a large .zarr file) that I am reading in as a dask array, compute_fixed_resolution_buffer fails when called by the image viewer.

The culprit is this line:
https://github.com/glue-viz/glue/blob/84ed937df55bd52966f9e094b1a8849c6c9bd8a1/glue/core/fixed_resolution_buffer.py#L256
which is returning a dask array rather than a numpy array so that `array = array[translated_coords]` a few lines down fails with a warning that dask arrays do not support fancy indexing. 

`NotImplementedError: Don't yet support nd fancy indexing
`

One simple solution is simply to explicitly cast `array` as a `np.array`

I don't yet have a minimal reproducible version of this bug (and the example .zarr file is 35 GB), so right now this issue is mainly to remind me of this problem :) I can read in other .zarr files without a problem, so this is something about the dimensions, chunking, or something else as-of-yet-undetermined about this particular file and how it translates to dask arrays.

**Comment by astrofrog** [comment]
Interestingly the comment a few lines up suggests I did have it working with dask arrays at some point but not sure why it isn't working anymore.

**Comment by jfoster17** [comment]
Oh, it works like a dream with *most* dask arrays, just... not all of them for reasons I have yet to uncover.

**Comment by jfoster17** [comment]
Okay... I think I have figured it out. The problem comes from the zarr [reader library](https://ome-zarr.readthedocs.io/en/stable/) I am using which uses dask_delayed to generate a full image out of multiple "wells". This library probably ends up calling a delayed function inside another delayed function, leading to this problem of needing to call compute twice

https://stackoverflow.com/questions/56944723/why-sometimes-do-i-have-to-call-compute-twice-on-dask-delayed-functions

(this is why I was unable to reproduce the behavior with anything except this specific file that is constructed out of multiple wells). 

So this is kind of something to fix in the reader library, but I'm tempted to have glue double-check that we're getting a proper numpy array back (and cast to an array if not) because it's possible other sources of dask arrays might also produce these double-delayed arrays.
