### ISSUE TITLE
Custom data viewer is not working

### ISSUE THREAD

**Issue by Gabriel-p** [glue-viz/glue#2420]
**Describe the bug**
Title

**To Reproduce**

Followed the instructions given here https://docs.glueviz.org/en/stable/customizing_guide/custom_viewer.html, ie added the first block of code to my `config.py`.

**Expected behavior**
Be able to load the `Shot Plot` new custom viewer

**Screenshots**
![Captura de pantalla de 2023-06-13 11 32 30](https://github.com/glue-viz/glue/assets/6054951/6321a874-232e-4efa-8788-8a32c013ac95)

**Details:**
Nothing happens as shown in the screenshot above, no errors in the console.

- Operating System: elementary 7 (based on Ubuntu 22.04.2 LTS)
- Python version (``python --version``): 3.11.3
- Glue version (``glue --version``): 1.11.0
- How you installed glue: pip

**Additional context**

**Comment by jfoster17** [comment]
This sounds vaguely familiar. Is the problem just that the axes aren't being reset? That is, if you change the limits in the plot to zoom out (you may have to use the zoom/magnifying glass to do it manually) will it appear?

**Comment by Gabriel-p** [comment]
Zooming has no effect. I also have no way of controlling the dataset as you can see in the lower left corner, there's nothing there:

![Captura de pantalla de 2023-06-13 14 48 31](https://github.com/glue-viz/glue/assets/6054951/cc263d7e-6c2e-447e-8b07-d5dcc750ff07)

**Comment by Gabriel-p** [comment]
BTW, other views work just fine:

![Captura de pantalla de 2023-06-13 14 51 42](https://github.com/glue-viz/glue/assets/6054951/440ea0ee-9bf9-4c7e-8858-be47d4fbcaef)

**Comment by jfoster17** [comment]
Sorry, I meant zooming out (right-click and drag the magnifier tool). The data lie between x (-250, +250) and y (0, 300).

**Comment by Gabriel-p** [comment]
You are correct, there it is! I'll close this issue now. Do you know why I don't get any options to edit the data (size, font, limits, axis, legend, etc)?

![Captura de pantalla de 2023-06-13 15 20 47](https://github.com/glue-viz/glue/assets/6054951/0de138b3-fe66-482a-bfce-1fc6a2add34b)

**Comment by jfoster17** [comment]
Simple viewer options come [later](http://docs.glueviz.org/en/stable/customizing_guide/custom_viewer.html#shot-chart-version-3-widgets) in the tutorial. Most of the other customization options actually require a bit more logic on the backend and you would need to use a [full custom viewer](http://docs.glueviz.org/en/stable/customizing_guide/viewer.html).

I'm going to re-open this issue if you don't mind -- we should fix this bug so that simple custom viewers resize to the data.

**Comment by jfoster17** [comment]
> Also if you don't mind, could you tell me how to make a simple scatter plot? I've been trying to get one to plot all morning and nothing. I need to generate three scatter plots and a simple histogram but I can't get past generating even a single scatter plot

Maybe I don't understand what you want, your "BTW, other views work just fine:" comment includes a screenshot of a scatter plot (with a categorical variable on one axis, but still).
