### ISSUE TITLE
TST + BUG: dev testing is not picking up numpy-dev

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#2469]
Something in your stack is downgrading numpy to 1.26.x so you are not picking up numpy 2.0.dev in your test suite even though you ask tox to install numpy-dev for that env.

As a result, you are not catching numpy 2.0.dev incompatibilities in your stack.

Blocks:

* https://github.com/spacetelescope/jdaviz/pull/2572

**Comment by dhomeier** [comment]
Working on that in #2471 , but the blocker here is probably shapely as well.
