### ISSUE TITLE
glue 1.19.0 broke jdaviz (cubeviz)

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#2483]
**Describe the bug**

CI failure as reported in:

* https://github.com/spacetelescope/jdaviz/issues/2805

**To Reproduce**

Install glue-core 1.19 and jdaviz from `main`, then run jdaviz test suite.

**Expected behavior**

Jdaviz CI should not fail.

**Comment by pllim** [comment]
These PRs were highlights in release notes.

* #2481
* #2478
* #2480
* #2475
* #2479

jdaviz does test against dev version of glue stack including glue-core and its devdeps job passed just yesterday (https://github.com/spacetelescope/jdaviz/actions/runs/8690877255/job/23831779573), so whatever that is failing jdaviz must have been merged and released before we had a chance to test against glue-core dev again.

**Comment by pllim** [comment]
So I think that narrowed it down to either of these:

* #2478
* #2480 

cc @astrofrog

**Comment by astrofrog** [comment]
I can git blame it later and see what caused it
