### ISSUE TITLE
pip installation instructions do not include gui

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#2494]
The pip installation instructions here:

https://docs.glueviz.org/en/stable/installation/pip.html

do not include installation of frontends, e.g., glue-qt, and therefore `pip install glueviz` results in uninstalling the command-line app `glue`.

**Comment by astrofrog** [comment]
I had forgotten to add glue-qt to the glueviz meta-package following the splitting out of glue-qt. I have now done this and released glueviz 1.3.0 which should work as expected. Please feel free to open a new issue if not!
