### ISSUE TITLE
Viewers are not saved properly on the main branch

### ISSUE THREAD

**Issue by Carifio24** [glue-viz/glue#2512]
**Describe the bug**
Something very bad that I noticed - using `glue-core` off of the main branch of this repository, viewers are not properly restored from a Qt session. 

**To Reproduce**
Use the current dev version of glue, together with the newest glue-qt:
*  `pip install git+https://github.com/glue-viz/glue`
* `pip install glue-qt`

**Expected behavior**
Viewers should be saved into the session file

**Screenshots**
Here's a video of this in action
https://github.com/user-attachments/assets/f353c686-ddb4-420b-9362-3729037083d4

**Details:**

- Operating System: Ubuntu 22.04
- Python version: Python 3.11.9
- Glue version: dev
- How you installed glue: [e.g. conda or pip]

**Additional context**
Note that this works fine if I use the currently released version of `glue-core`. I would suspect #2510 as a possible cause, but to be honest I don't have a great handle on the serialization functionality as I've never really had a need to delve into it. Pinging @astrofrog in case he has thoughts on that.

**Comment by astrofrog** [comment]
Can you try glue-core dev with glue-qt dev?

**Comment by Carifio24** [comment]
It doesn't look like glue-qt has any new commits since the last release

**Comment by Carifio24** [comment]
@astrofrog So I was using the newest release of glue-qt, which I assumed was `0.3.2` (which is up-to-date with the main branch there), but it looks like the newest version on PyPI is `0.3.1`. I guess the release CI failed?

**Comment by Carifio24** [comment]
I'll close this as things do work correctly using the dev versions of both packages.
