### ISSUE TITLE
Crisp fonts and images on retina displays

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#282]
The images aren't being sampled properly, and look a bit fuzzy on retina

**Comment by astrofrog** [comment]
Some but not all of the issues are resolved in PyQt5 (for example in PyQt5, the icons in the menus are fine, but not on the buttons).

Icons in buttons: http://stackoverflow.com/questions/32549455/hdpi-retina-icons-in-pyqt4-or-pyqt5

Matplotlib plots: https://github.com/matplotlib/matplotlib/issues/4977

**Comment by astrofrog** [comment]
Marked this as upstream fix required since I think the only remaining improvement is that Matplotlib needs to support retina displays with PyQt5.

**Comment by astrofrog** [comment]
I think this is all fixed with Qt5
