### ISSUE TITLE
Profile fitting plugin interface

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#287]
I'm interested in @keflavich and @astrofrog's thoughts here

I'm working on a spectrum/profile extraction utility in Glue that, among other things, allows users to fit models to profiles. It looks like this currently:

![image](https://f.cloud.github.com/assets/796752/2500556/a00f33b2-b363-11e3-886f-da293ffaf8e1.png)

I'd like to make it easy for users to plug in their own model fitting code (maybe from astropy, or something homegrown). Here's a possible interface:

``` python

class GaussianModel:
    label = "Mixture of Gaussians"
    n_components = ChoiceOption([1, 2, 3], label="Number of Gaussians")
    option_2 = FloatOption(min=0, max=3, label="Option 2")
    option_3 = IntOption(min=0, max=100, label="Option 3")
    fixed_at_zero = BoolOption(label="Fix baseline at 0")

    def fit(x, y, dy, **params):
        ...fit code here...
        predictor = (callable that maps model(x) -> prediction)
        report = "Converted successfully. Mean=1, stdev=3,..."
        return self.fit_result(predictor, report)
```

Given a class like this, Glue would:
- Add a "Mixture of Gaussians" option to a model selection dropdown menu
- When that model is chosen, construct a basic form like:

![image](https://f.cloud.github.com/assets/796752/2500735/660f0e6a-b365-11e3-833e-579ea6bff5ba.png)
- When the fit button is pushed, extract x, y, dy, and the settings of each Option, call the fit method, and use the result to plot the model, residuals, and text summary

I think such a class is simple enough that any python coder could roll their own basic fitting plugin based on an example tutorial. My main questions are:
- Do you agree?
- Are enough arguments passed to `fit`, or do some models need more?
- What kinds of `Options` are needed when building the form UI?
- What kinds of things would you want to do with a fit result from Glue?

**Comment by astrofrog** [comment]
Just as an update on this, @keflavich and I have been working on a more sophisticated spectral viewer in Glue based on pysepeckit: https://github.com/glue-viz/glue-pyspeckit-plugin

**Comment by astrofrog** [comment]
I think the original intent was this issue was actually implemented as fitter plugins in glue by @ChrisBeaumont - http://glueviz.org/en/stable/gui_guide/spectrum.html#custom-fitting-plugins
