### ISSUE TITLE
3D scatterplots?

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#294]
I generally don't like 3D scatter plots for statistical data, but plotting spatial point clouds in 3D space makes sense

**Comment by astrofrog** [comment]
We have an issue open for this in the glue-3d-viewer repo: https://github.com/glue-viz/glue-3d-viewer/issues/9 - Matplotlib is very slow, but VisPy should be a lot faster.

**Comment by astrofrog** [comment]
This is now done in the [glue-vispy-viewers](https://github.com/glue-viz/glue-3d-viewer) plugin!
