### ISSUE TITLE
[wishlist] add an option for coloring scatter plot points based on data

### ISSUE THREAD

**Issue by yarikoptic** [glue-viz/glue#403]
E.g. by selecting one of the (ordered, e.g. numbers ;-)) attributes to define colors of the points, thus effectively visualizing a 3rd dimension within the 2d scatter plot.  Here is an example of scatter plotting (homebrewed scripts) of two neuroimaging volumes:
![scatter](https://cloud.githubusercontent.com/assets/39889/3528941/3f548b82-0794-11e4-9e78-382ee4176d36.png)
where y coordinate was used to color the scatter plot, immediately (without brushing) providing a clue about location of extreme points

I know that it would interfer with brushing feature, but may be with a choice of colormaps to be used

**Comment by astrofrog** [comment]
Note that we now have a plugin called [glue-vispy-viewers](https://github.com/glue-viz/glue-vispy-viewers) that implements 3D viewers based on VisPy, and allow e.g. color-coding of points by attributes, etc. We should add 2D viewers to that plugin too in the same way (in that plugin for now).

@rossant @yarikoptic - is this something you are still interested in helping with?

**Comment by PennyQ** [comment]
@astrofrog just wanna let you know we got this wish-list mentioned on the group meeting today :)

**Comment by astrofrog** [comment]
This has been implemented using Matplotlib in #1358 and will be in v0.11, and I'll investigate OpenGL solutions for future releases.
