### ISSUE TITLE
Rendering artifacts when zooming?

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#424]
When I zoom in on an image that contains NaNs (which I'm not sure is necessary information but it might be), I see imaging artifacts where very large pixels are displayed, apparently from a different zoom level.  The best example I can reproduce at the moment is attached.
![renderingartifcatsglue](https://cloud.githubusercontent.com/assets/143715/3640929/40b5bcc4-10ab-11e4-91e3-2de1e9dad49a.png)

**Comment by astrofrog** [comment]
@keflavich - are you still seeing this issue?

**Comment by keflavich** [comment]
Not sure, sorry.  I'll add more info if it recurs.
