### ISSUE TITLE
Possible qt issue: scatter plot stuck in front of others?

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#483]
I have a Glue session in which I can control the relative order of some windows (i.e., which is 'on top' in the matplotlib zorder sense), but one plot window is 'stuck' on top of the others; I can't bring anything in front of it.  

Is there a way to control qt 'stickiness' behavior?  Is this a bug?  

The Glue session was started with:
```
... data loading snipped ...
app = GlueApplication(dc)

# plot x vs y, flip the x axis, log-scale y axis
scatter = app.new_data_viewer(ScatterWidget)
scatter.add_data(catalog)
scatter.yatt = catalog.id['temperature_chi2']
scatter.xatt = catalog.id['higaldusttem']
#scatter.xflip = True
#scatter.ylog = True

viewer = app.new_data_viewer(ImageWidget)
viewer.add_data(cube)
viewer.add_data(catalog)

app.start()
```

**Comment by astrofrog** [comment]
@keflavich - I've never seen this issue - can you confirm whether you have seen it recently?

**Comment by keflavich** [comment]
Not lately, but I haven't been experimenting with layout much lately either.
