### ISSUE TITLE
Exporting matplotlib plotting scripts

### ISSUE THREAD

**Issue by yuvallanger** [glue-viz/glue#498]
In the video editing program Kdenlive one can, instead of directly rendering the video, create a shell script with all the rendering operations Kdenlive would have used to create the video file.

An equivalent feature in Glue would be very useful - creating a matplotlib plotting script that, when executed, will create the figures displayed.

If I wanted to contribute such a patch, where would I start?

**Comment by astrofrog** [comment]
I might take a stab at this soon - I think we should store the data in a JSON file (essentially in a similar format to what we use for the full session file). We could then include the data in the file by default but also allow it to be referenced like for session files (we can re-use a lot of that machinery).

**Comment by astrofrog** [comment]
This can now be done from the main built-in viewers, so closing!

http://docs.glueviz.org/en/stable/whatsnew/whatsnew.html#export-python-scripts
