### ISSUE TITLE
Use PyContracts and Diff-Cover?

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#506]
I learned of two cool projects at a recent python meetup, and I wonder if either/both are worth integrating into Glue:

[PyContracts](http://andreacensi.github.io/contracts/) provides a python 2/3 compatible syntax of specifying type/value constraints on function inputs and outputs. It uses that information to perform runtime analysis to see if any constraints are violated. I like it because the contracts are useful documentation, they can detect code quality issues, and the runtime checking can be disabled by default for non-developers. 

[diff-cover](https://github.com/edx/diff-cover) specifically measures test coverage changes on the diffs of each commit, and can be configured to, for example, trigger travis failures if modified code isn't sufficiently tested. It's a nice way of incrementally improving test coverage, by focusing on the code you're most familiar with at the moment (the code you just changed).

**Comment by astrofrog** [comment]
The pycontracts part was done in #512. Also we use coveralls for coverage checking and this tells us how much coverage has increased/decreased in a PR, which I think is good enough, so I'll go ahead and close this.
