### ISSUE TITLE
A package for writing easy command-line interfaces

### ISSUE THREAD

**Issue by yuvallanger** [glue-viz/glue#510]
I've watched a [talk] describing a few Python packages which make it extremely easy to write command line interfaces.

The package [Begins] looks really cool. It can greatly reduce the complexity of the command line interface code.

Would you be interested if I experiment a bit with converting the command-line interface code into Begins?

[talk]:http://www.pyvideo.org/video/3175/the-command-line-interface-because-why-not
[begins]:http://begins.readthedocs.org/

**Comment by astrofrog** [comment]
Just to make sure I understand, would this add a new language/syntax that would replace the current pure-ipython shell?

**Comment by ChrisBeaumont** [comment]
As I understand the proposal here is to use something besides the builtin optparse/argparse to refactor `main.py`, and potentially add more options to the glue command line program. It wouldn't replace the IPython terminal in the GUI (or the experience of importing Glue from python)

**Comment by astrofrog** [comment]
I'm going to close this for now - I'm not sure if this is really needed.
