### ISSUE TITLE
Make it so that glue can be installed with conda

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#542]
Ideally it would be nice if glue could be included in the default conda repository, but otherwise it could have its own channel. The downside would be that it could only install dependency packages that are already in conda (or in that channel).

**Comment by astrofrog** [comment]
On the other hand, it could be a pain to maintain. It would be worth asking the continuum folk if they can include it in the default conda channel

**Comment by ChrisBeaumont** [comment]
How hard / user-inconvenient do you think it would be to host a custom binstar channel? That would give more flexibility with dependencies

**Comment by astrofrog** [comment]
@ChrisBeaumont - it's easy enough to set up a channel (we did it with astropy), the main difficulty is making sure we build conda packages for all platforms, so it requires maintaining some virtual machines. I can try and set something up and see how much work is required.

**Comment by astrofrog** [comment]
I am currently working on this repo: https://github.com/glue-viz/conda-package-builder (forked from another I found) which will build most of the windows and linux conda packages (and maybe we can build the mac ones too with a different repo and .travis.yml file)

**Comment by astrofrog** [comment]
The conda packages are here: https://binstar.org/astrofrog/glueviz/files - still untested for now. There is an issue that the conda package shouldn't depend on numpy version, so working on that.

**Comment by astrofrog** [comment]
Great, Travis can be used to make the MacOS X conda package too:

https://binstar.org/astrofrog/glueviz/files

This uses a separate repository:

https://github.com/glue-viz/conda-package-builder-macosx

because it needs a different Travis file.

The only one missing is the Linux 32-bit. Maybe lower priority for now. I can set up a VM later. I'll leave this open until the issue with the numpy versions is resolved (I have an open issue with Continuum)
