### ISSUE TITLE
Add a section to the website on creating new derived components

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#554]
In particular, how double clicking dataset components adds them to the expression, and what operators are supported (including ``np.function`` and any modules/functions imported in the ``config.py` file)

cc @jegpeek

**Comment by stargaser** [comment]
I'm interested in working on this documentation item. I've just started working with custom components and data loading functions with Glue.

**Comment by astrofrog** [comment]
@stargaser - great! Let us know if you need any help/advice for writing the sphinx docs and/or submitting a PR. You can always start simple and then we can iterate on it, add screenshots if needed, etc.

**Comment by ChrisBeaumont** [comment]
@stargaser glad to hear it! Please let us know how you get on, if there are pain points we can smooth over, etc.

**Comment by stargaser** [comment]
@astrofrog @ChrisBeaumont I propose to add a new section "Defining a New Component" to the "User Interface Guide", right before "Building Custom Subsets with the Terminal Window". I'll use the W5 dataset as an example. Does this look like the right place to you?

It could go under "Getting started" but my feeling is that the topic is a bit advanced for that.

**Comment by ChrisBeaumont** [comment]
Yes, that sounds like a good place to put it.

**Comment by astrofrog** [comment]
@stargaser - I'm not sure whether you have started on this yet, but just in case you have, I just thought I should mention that I have fixed the ability to build the docs (was broken with Astropy 1.0) and I've also reorganized the file a little. The getting started stuff is now in a sub-directory. Let me know if you have any issues rebasing.

If you haven't started yet, then just make sure you update to the latest version in master before beginning :)

**Comment by stargaser** [comment]
@astrofrog - Thanks for the warning. I hadn't quite started yet so I've just updated my fork.

**Comment by stargaser** [comment]
I've opened a pull request #572 . I just edited the .rst file in TextWrangler. Will it be obvious whether it worked? Is there some sort of .rst syntax checking I should do before the pull request?

**Comment by astrofrog** [comment]
@stargaser - thanks! The best way to check if it works is to do ``make html`` inside the ``doc`` directory then look at the output in ``_build/html/index.html``. I will review #572 very soon.

**Comment by stargaser** [comment]
@astrofrog - aha, that worked to build the docs. I see my images are too large. The last one looks best without specifying :width: 60%.

**Comment by stargaser** [comment]
Is the convention to referring to GUI buttons and other elements to use double back-quotes?
e.g. I should refer to the ``w5_psc`` data item and say to click the ``OK`` button, right?

**Comment by astrofrog** [comment]
@stargaser - yes, that would be fine, thanks!

**Comment by stargaser** [comment]
In the section "Adding new attributes to datasets" of the Python Guide, it is shown how to define new components in Python or the IPython window. These are called "attributes" instead of "components".

1. Should we use "components" or "attributes"?
2. Should I include a reference to this Python section in the GUI guide?
3. Will components/attributes ever have units like astropy's Table?

**Comment by astrofrog** [comment]
@stargaser - sorry for the delay. In the mean time I removed that old section from the Python guide so I think the issue is moot. Feel free to open a new issue or pull request if you think we can improve things further!
