### ISSUE TITLE
Develop a custom_tool class to make it easy to create new tools in the toolbar

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#560]
At the moment, developing a new tool for the toolbar requires a fair amount of knowledge of the internal workings of glue. However, there isn't any reason why we can't abstract a way all the details, at least for simple cases. One could imagine having a `custom_tool` class, similar to `custom_viewer`, that makes it easy to develop new tools.

**Comment by ChrisBeaumont** [comment]
What kind of functionality do you envision exposing for a custom_tool? 

Perhaps one place to start is to look at whether the MouseModes could be more easily subclassed/extended. Those classes implement a lot of the logic to draw shapes on plots and work with the results.

**Comment by astrofrog** [comment]
@ChrisBeaumont - yes, I was also thinking along the lines of subclassing/extending mouse modes.

Here's an example use case: say we want to develop a tool where the user can select a rectangular region, do some calculation on the subset, and pop up a scatter plot with the results - really all that should be needed is to say 'I want to make a tool where the user selects a rectangular region and calls this callback function'. One could imagine having something (in pseudo code) like:

```
class SpectrumTool(RectangularMouseMode):

    def on_complete(self, subset):
        # do stuff with subset
        # initialize scatter plot/widget with data
```

**Comment by astrofrog** [comment]
So I think in terms of functionality that could get exposed, one could envision that we'd have the option to include callback functions, an icon for the toolbar, some metadata.

Of course, this won't cover all use cases, but something like this to start with could already open up the possibilities for people to add modes to the toolbars reasonably easily (I know @jegpeek is interested in this)

**Comment by ChrisBeaumont** [comment]
That makes sense. The details of this are tricky -- you want to strike a good balance between encapsulation, ease of use for beginners, and scalability, and those three considerations are going to conflict at some level when deciding how much information to expose to a custom tool like this. 

Perhaps the best idea is to start by optimizing for a specific concrete use case (@jegpeek has several), and dealing with consequences down the road :)

**Comment by astrofrog** [comment]
@ChrisBeaumont - I agree about just trying different use cases. I wrote a small spectrum-like plugin for @jegpeek and @yhzheng's spectrum extraction code for GALFA:

https://github.com/astrofrog/galfaglue/blob/plugin/galfaglue/plugin.py

and writing that is what prompted me to open this issue (at the moment, that plugin relies very much on knowing the internals of glue and hidden methods on the existing spectral extraction tool). I'm going to see how one could write it with the type of API described in this issue instead.

**Comment by astrofrog** [comment]
I have opened a PR to an experimental repository with an example of a custom tool to start thinking about API:

https://github.com/glue-viz/glue-experimental-plugins/pull/1

Comments on that welcome!

**Comment by astrofrog** [comment]
This has since been done! Closing this.
