### ISSUE TITLE
Could not import extension astropy.sphinx.ext.astropyautosummary

### ISSUE THREAD

**Issue by nilswagner** [glue-viz/glue#563]
How can I resolve the following problem

nils@linux-5jkt:~/git/glue/doc> make latex
sphinx-build -n -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.2.3

Extension error:
Could not import extension astropy.sphinx.ext.astropyautosummary (exception: No module named sphinx.ext.astropyautosummary)
Makefile:100: recipe for target 'latex' failed
make: *** [latex] Error 1

**Comment by astrofrog** [comment]
@nilswagner - this will require the changes in https://github.com/glue-viz/glue/pull/555 (it is due to a change in astropy)

**Comment by astrofrog** [comment]
@nilswagner - this is fixed in the latest version from master - let me know if you are still having issues!

**Comment by nilswagner** [comment]
nils@linux-5jkt:~/git/glue/doc> make latex
sphinx-build -n -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.2.3

Exception occurred:
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 287, in
fetch_build_eggs
    replace_conflicting=True,
TypeError: resolve() got an unexpected keyword argument
'replace_conflicting'
The full traceback has been saved in /tmp/sphinx-err-ZxesM1.log, if you
want to report the issue to the developers.
Please also report this if it was a user error, so that a better error
message can be provided next time.
A bug report can be filed in the tracker at <
https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Makefile:100: recipe for target 'latex' failed
make: *** [latex] Error 1


On Tue, Feb 24, 2015 at 8:18 PM, Thomas Robitaille <notifications@github.com

**Comment by astrofrog** [comment]
@nilswagner - what is the output of:

```
python -c 'import setuptools;print(setuptools.__version__)'
```

?

**Comment by astrofrog** [comment]
@nilswagner - could you also post the full exception from the ``/tmp/sphinx-err-ZxesM1.log`` log file?
