### ISSUE TITLE
Issue with S3 upload of docs

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#568]
Seems to raise an error:

```
if [ `git symbolic-ref -q --short HEAD` == 'master' ]; then aws s3 sync _build/html s3://docs.glueviz.org/en/latest; fi
/bin/sh: 1: [: ==: unexpected operator
```

Appears to have been broken for a little while.

@ChrisBeaumont - any idea what is going on in this case?

**Comment by astrofrog** [comment]
(I can also look into it, but wondering if it's been a known issue)

**Comment by ChrisBeaumont** [comment]
Hm this works for me *unless* I checkout an explicit revision and enter "detached head state"

```
#cbeaumont:glue cbeaumont$ git branch
* (detached from d2595d5)
  master
  tmp
#cbeaumont:glue cbeaumont$ git symbolic-ref -q --short HEAD # nothing
```

It works for me if I'm on a named branch.

The relevant fix would then be something like

```
`git symbolic-ref -q --short HEAD || echo '---'`
```

Unless you are getting an error in situations where you expect the test to pass

**Comment by astrofrog** [comment]
Ok, thanks! This is happening on the master branch on Travis (just realized I forgot to say that above). Which should be a real branch. I will investigate.

**Comment by astrofrog** [comment]
I'll do some debugging on Travis in my glue fork (will print out ``git symbolic-ref -q --short HEAD`` and ``git branch`` to see what might be going on).

**Comment by ChrisBeaumont** [comment]
Yeah maybe travis switched its logic for how it checkouts repositories, such that it worked before but doesn't now. In any event we just need to change the test so that it compares the sha1 of the current working directory against the sha1 of master.

**Comment by astrofrog** [comment]
It's a pain that we can't use the ``TRAVIS_BRANCH`` env variable:

> TRAVIS_BRANCH:For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master)

(because for PRs it will be ``master``)

**Comment by astrofrog** [comment]
Ah but we can use TRAVIS_PULL_REQUEST=false/true too!

**Comment by astrofrog** [comment]
Although if we do that it won't work when not on Travis. One option is to remove the if statement from the Makefile and insert it in the ``.travis.yml`` file. But in any case, something like

```
[ $TRAVIS_BRANCH == master and $TRAVIS_PULL_REQUEST == false ]
```

should work.

@ChrisBeaumont - can you clarify why the if statement is currently in the Makefile and not in .travis.yml? Is it to make sure that you don't ever change the live docs locally accidentally?

**Comment by ChrisBeaumont** [comment]
It would be fine to put the logic in `.travis.yml`

**Comment by astrofrog** [comment]
@ChrisBeaumont - I've put the changes in a PR (https://github.com/glue-viz/glue/pull/569) so you can see if you agree
