### ISSUE TITLE
Write documentation on how to write a full Qt plug-in data viewer widget

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#583]
In particular, this should make clear what the widget should inherit from, and what API/methods it should provide. I can look into this in the near future.

**Comment by ChrisBeaumont** [comment]
Yeah this would be useful esp. to folks at JWST like @stscieisenhamer interested in developing spectral tools in Glue. In fact, my opinion is that the documentation should focus on building a simple spectral-like visualizer

**Comment by astrofrog** [comment]
This now exists here: http://glueviz.org/en/stable/customizing_guide/full_custom_qt_viewer.html - it can still be expanded, but I think this is fine for now.
