### ISSUE TITLE
How to deal with growth of plugins over time

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#596]
Discussions in #593 open up the door for many more possible plugins to glue, and I think we should try and think of how we want to deal with that growth over time and which plugins should live in the main glue repository.

Submodule
--------------

One option that I mentioned briefly in #593 is to develop 'official' and curated plugins in a separate ``glue-plugins`` repository that would be included as a sub-module at ``glue/plugins`` in the main repository. This would help us conceptually isolated the development of core functionality vs plugin functionality.

This is not without issues though:

* We would need to know from a pull request to the plugin repository if it will break something in the core. This can be done by making sure that the Travis build actually clones the core repository and imports the latest plugin submodule to test, to make sure that they will work 'in-place'

* We would need to make sure that the submodule is automatically added when doing ``setup.py install``, though we do that in astropy and it works reasonably well

* We would need to update the hash of the submodule regularly in the glue repository, which is a bit of a pain (based on experience in astropy core)

Tar file releases could include all the plugins by default so for the average user, nothing would change from now.

Extra package(s)
-----------------------

Another possibility would be to do what pytest does and simply have extra packages for plugins. We could imagine breaking this up into e.g. domains, so for example ``glue-plugin-astro``, etc. So then users can pip install whatever plugins they want.

This also allows for a separate release cycle for plugins and core, though a downside is that plugin versions may be dependent on core versions.

Status quo
--------------

We could just push all the plugins we like into the core repo and then worry about it if it becomes unmanageable. The reason I want to have some discussion now is because if we start coming up with specialized things like e.g. a Vizier importer, which is quite specialized, it's worth thinking about where that should live.

A combination
-----------------

We could include very important plugins in ``glue/plugins`` and have separate packages for others, but the difficulty here is determining what is important and what is not?

**Comment by astrofrog** [comment]
In any case in the mean time we can use https://github.com/glue-viz/glue-experimental-plugins for experimental plugins :) There's no rush on this discussion.

**Comment by ChrisBeaumont** [comment]
I'm personally against the git submodule approach. I think they're really confusing. The pytest approach of separate packages sounds more sensible. I think it's also pretty standard for a tool supporting plugins to have a builtin plugin manager. If glue is able to install plugins automatically, then it's easy to maintain a list of standard plugins in `config.py`, and have glue download/update them, if necessary.

**Comment by astrofrog** [comment]
I worked with the pytest plugin framework in the last couple of days and discovered a way that I wasn't aware of before, which is to use entry points in the plugin packages:

http://pylons-webframework.readthedocs.org/en/latest/advanced_pylons/entry_points_and_plugins.html

Basically, a plugin package's ``setup.py`` would include something like:

```
entry_points="""
    [cms.plugin]
    jpg_image=image_plugin:make_jpeg_image_plugin
    png_image=image_plugin:make_jpeg_image_plugin
""",
```

and then glue can easily discover all installed plugins.

I'm going to do some tests with that to see if it would work in our case, but I'm pretty sure it will.

**Comment by astrofrog** [comment]
Also, when we do a tarfile release, we could bundle common plugins that we want to include in a release.

**Comment by astrofrog** [comment]
This is now implemented :)
