### ISSUE TITLE
Develop a GUI plugin browser/selector

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#602]
It would be cool to have a built-in GUI browser for plugins that would allow users to enable/disable plugins as well as install them locally. I think we'll need to start using some kind of ``~/.glue`` directory to store that kind of config as well as downloaded plugins.

**Comment by ChrisBeaumont** [comment]
Agreed (and we already use the notion of `~/.glue` for the config stuff)

**Comment by astrofrog** [comment]
I need to check if we can also use the concept of namespace package here

**Comment by astrofrog** [comment]
### GUI vs command-line

If we come up with a GUI to manage plugins, the question is whether we then also continue to allow plugins to be enabled via the ``config.py`` file, and I think the answer is yes, but this then means that there is a kind of global user-level config that lives in ``.glue``, and that the local ``config.py`` file can then choose to override the global settings. So the GUI would serve the purpose of setting global preferences re: plugins that persist across sessions.

### Dependencies

One difficulty to keep in mind is that some plugins may require e.g. VTK or other packages not included in glue. In that case, I don't think there is any way other than requiring the plugin to be installed by hand (with e.g. pip or conda) along with its dependencies. But what would be nice is that once it is installed, it appears in the GUI manager.

### Enable/Disable vs Search

There are two purposes for a GUI. One is to enable/disable installed plugins, and the other is to search for and install new plugins. The latter may be tricky because of the point above that some plugins will have non-trivial dependencies. For this reason, it might be worth starting off with simply implementing an enable/disable GUI and then later on seeing if we want to allow installing from the GUI too (this will be important for the Mac App for example).

### Discoverability

In order for glue to discover what plugins are available, the easiest way would be to have ``glue.plugins`` be a namespace package inside which plugins install themselves. Then glue can simply search for all available submodules in ``glue.plugins``.

**Comment by astrofrog** [comment]
Another note - rather than search in ``glue.plugins``, the GUI could simply be an interface to the registries in ``glue.config`` and allow items to be removed/added to the registries. This would allow full customizability of many aspects of glue.

**Comment by astrofrog** [comment]
Very ugly prototype (doesn't actually work)

![screen shot 2015-06-23 at 10 21 06 pm](https://cloud.githubusercontent.com/assets/314716/8317535/31dc457e-19f6-11e5-824b-203c3ba08b4a.png)

Essentially the way to enable/disable components is that the registries would include a flag for enabled/disabled and we could enable/disable things on-the-fly.

Whenever plugins are installed, a line could be added to ``.glue/config.py`` adding these to the registry. For convenience, installed plugins could be installed by default and we could then keep a list of disabled registry items in ``.glue/disabled-plugins``.

Of course, as-is, this doesn't add *significant* functionality since most of this could be done before from the ``config.py`` file, but we could then add search functionality that for now would simply allow the user to follow a link to the repository page which would include instructions on installing (since installing plugins directly in glue would be tricky initially, due to dependencies).

**Comment by astrofrog** [comment]
(this is just brainstorming at this point, and taking notes to remember :) )

**Comment by astrofrog** [comment]
Now for plugin installation, there are two cases:

* For the non-Mac app (e.g. with conda, etc.) we *could* allow the user to install the plugin itself and simply warn them that they have to also install whatever dependencies the plugin has. Plugins could have a way of declaring (in the code itself rather than just in ``setup.py``) what the dependencies are. So then in the plugin browser we could have green ticks and red crosses - green ticks if all dependencies are installed, and red crosses if not, and hovering over the red cross would tell the user which dependencies are missing.

* For the Mac app, we could restrict installable plugins to those where all dependencies are already in the Mac app.

**Comment by astrofrog** [comment]
Assuming plugins are pure Python code, installation would then simply involve copying the package code (rather than formally installing them) into ``.glue``. Alternatively, we could call pip from glue. We could then even install dependencies that are pip installable.

**Comment by astrofrog** [comment]
If we do this, then we need a plugin registry, which could be a json file that lives in a GitHub repository and gets synced to e.g. http://www.glueviz.org/plugin_registry.json

**Comment by astrofrog** [comment]
The only part that needs to be implemented is the installation, for which we have a separate issue: https://github.com/glue-viz/glue/issues/765
