### ISSUE TITLE
Have a way to avoid converting data type on load

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#603]
I am reading in a FITS table which contains a column with Python major versions (i.e. 2.6, 2.7, 3.1, 3.3), and glue currently converts this to floating-point values on-the-fly, but I want to keep it as categorical string data. It would be nice to be able to select in the GUI whether to treat a column as a string or floating-point column.

**Comment by ChrisBeaumont** [comment]
Yeah this would be cool -- Sounds like another kind of custom importer/loader interface along the lines of #595, right?

**Comment by astrofrog** [comment]
Just to show my use case, I have a FITS table where all columns are strings (for reasons beyond my control):

![screen shot 2015-04-29 at 3 29 18 pm](https://cloud.githubusercontent.com/assets/314716/7393288/ced51704-ee84-11e4-986a-8ee257ae921d.png)

In this case, I want ``grid_name`` to be categorical, ``jobname`` to just be a string array (each one is different, so no point wasting time making it categorical), and I want ``mem`` to be a float array.

What I envisage would be that when we read a file in where there are string columns, we could pop up a window like @ChrisBeaumont is mentioning that shows what the 'views' of the data will be assumed to be, and at later times it will still be possible to double click on the dataset and change those assignments. Or we could just assume some defaults but then allow the user to go and change those by double clicking on the dataset and popping up that window.

**Comment by astrofrog** [comment]
I am going to try and think about this a bit on a :airplane: today

**Comment by astrofrog** [comment]
I'm going to close this in favor of https://github.com/glue-viz/glue/issues/980 (just trying to keep the number of issues down, and this will be solved by https://github.com/glue-viz/glue/issues/980 and https://github.com/glue-viz/glue/issues/981)
