### ISSUE TITLE
Values lost on "Open Session", relative values retained?

### ISSUE THREAD

**Issue by keatonb** [glue-viz/glue#606]
I'm new to glue but I'm seeing some unexpected behavior when I try to save and then open a session.  When I open the session, the plots all look correct except the axes seem to have lost information about the absolute values of the points plotted and instead show some sort of relative values (?).  It's hard to explain so here are pictures:

Before saving:
![before](https://cloud.githubusercontent.com/assets/6413923/7153156/35bfd360-e30d-11e4-88ef-dc3ad908ae67.png)
After saving, then reloading:
![after](https://cloud.githubusercontent.com/assets/6413923/7153159/3efb68e0-e30d-11e4-90e0-9da9169c77e0.png)

Notice the change of values on the x-axis.

Let me know what else I can do to help you understand this issue.  The data were loaded from a Pandas dataframe in an IPython Notebook with the call `glue.qglue(dr12=frame)`.

**Comment by ChrisBeaumont** [comment]
Huh, that's weird.

Can you print the dataframe in the notebook, and paste the result in this issue?

**Comment by astrofrog** [comment]
One thing that's curious is that in the first screenshot the limits of the histogram should be -0.5 to 80.5 but it's much smaller. Is that a bug even before the saving part?

**Comment by keatonb** [comment]
Good eye.
Digging further into my issue, I found the problem.  Some of the values in the dataframe were mistakenly stored as strings rather than floats.  Since the numbers displayed on the axes were in the expected range, I figured the values were being interpreted as I intended.  Of course one should not use strings to hold numerical values!

**Comment by astrofrog** [comment]
@keatonb - thanks for figuring it out!

@ChrisBeaumont - along the lines of what I suggested in https://github.com/glue-viz/glue/issues/603, it would be good to have a drop-down menu that shows what the current data type is and allows users to select e.g. float or string. What do you think?
