### ISSUE TITLE
glue starting QApplication prematurely

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#615]
If I run the following example on Python 2.7 with PySide installed:

```python
from PySide import QtGui
import sys

from glue.qt.qtutil import load_ui

app = QtGui.QApplication(sys.argv)
```

I get

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    app = QtGui.QApplication(sys.argv)
RuntimeError: A QApplication instance already exists.
```

which is annoying if I want to create a standalone app that imports some helpers from glue.

**Comment by astrofrog** [comment]
It looks like this is due to the following code in ``glue/qt/__init__.py``:

```
_app = get_qapp()
import atexit
atexit.register(teardown)
```

I feel like this should not happen here on importing ``glue.qt`` - @ChrisBeaumont, would you object if this was moved to specifically the ``glue`` command and the ``qglue`` function?

**Comment by ChrisBeaumont** [comment]
This early importing is actually important. There are 2 flavors of PyQt, and Glue only supports the newer version. MPL and IPython support both versions, although in some circumstances importing matplotlib will load the glue-incompatible version of Qt. By importing eagerly, we prevent this conflict.

The "glue pattern" is to never instantiate QApplication, and instead use `glue.qt.get_qapp()`. IPython and MPL have similar patterns. If you want a glue-agnostic pattern, then you can check to see if QtGui.QApplication.instance already exists.

**Comment by astrofrog** [comment]
@ChrisBeaumont - so just to make sure I understand, at what point do we 'lock' which version of PyQt we use? Is it at the point where we instantiate ``QApplication`` in ``glue/qt/__init__.py``?

Let's leave this open and I can add a note about ``get_qapp()`` to the source code and maybe to the docs.

**Comment by ChrisBeaumont** [comment]
>  Is it at the point where we instantiate QApplication in glue/qt/__init__.py?

Yes, as soon as glue.qt gets imported we [call get_qapp](https://github.com/glue-viz/glue/blob/master/glue/qt/__init__.py#L5), set up a QApplication, and [freeze PyQt](https://github.com/glue-viz/glue/blob/master/glue/external/qt.py#L53) if needed

**Comment by astrofrog** [comment]
This is no longer relevant since ``glue.qt`` no longer exists, and we launch the application as needed.
