### ISSUE TITLE
Separate out Qt wrapper into separate package?

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#620]
One thing that is very useful in glue that could be useful to other packages is the code in https://github.com/glue-viz/glue/blob/master/glue/external/qt.py. I would like to propose that we split this out into a separate repository (though we can include a copy in glue) so that any package using Qt could choose to use this. This is important for the use case where I want to develop a widget that can be used outside glue - in that case, I still want to be importing from that module to make sure that I use the correct Qt wrapper, but having glue as a dependency seems overkill.

**Comment by ChrisBeaumont** [comment]
Sounds good to me (at this point similar versions of this code exist in Glue, MPL, and IPython)

**Comment by astrofrog** [comment]
I wonder if we should start from the latest version in IPython, since that appears to also support PyQt5. I can take a look. We should also include some version of ``load_ui`` here (that is glue-agnostic)

**Comment by astrofrog** [comment]
@ChrisBeaumont - I've started doing this in https://github.com/glue-viz/qt-helpers

**Comment by astrofrog** [comment]
Closing, since this is now done in qt-helpers :)
