### ISSUE TITLE
Feature request: Implement a ds9 like multi-image viewer

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#624]
I need to check if this is already possible with the ginga widget, but a feature that was requested is to have an image viewer that can have multiple sub-plots to show images in different bands for example, that can support ds9-style 'match wcs' (using on-the-fly reprojection with interpolation).

If this is not already possible, it could be developed as a separate widget, then glue-yfied later.

**Comment by ChrisBeaumont** [comment]
@ejeschke and I brainstormed about doing this with Ginga. I think the stopgap when we spoke last was that Ginga didn't have an easy way to independently adjust the brightness transfer function for each color layer. I'm also not sure to what extent it supports on-the-fly reprojection, though it's certainly better-positioned than MPL to do so

**Comment by astrofrog** [comment]
I'm going to close this as the image viewer now supports on-the-fly reprojection and I don't think the subplots are really needed since that can be done with multiple image viewers.
