### ISSUE TITLE
Make it easy for users to add new data to glue once qglue has been launched

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#629]
This may already be possible, but if so we need to document it - Harry Ferguson mentioned he would like to be able to do something like:

```
>>> app = qglue(data=...)
>>> app.add_data(more=...)
```

and have the new data appear in glue automatically.

**Comment by ChrisBeaumont** [comment]
Right now the only supported syntax is `app.data_collection.append(...)`, but that doesn't do the same kinds of smart-parsing that qglue does. +1
