### ISSUE TITLE
Problem plotting histogram and scatter plots

### ISSUE THREAD

**Issue by Techn0logic** [glue-viz/glue#631]
I am able to display volume data with image viewer but when I drag to display histogram view or scatter plot view I get an error TypeError: SliceWidget.mode_changed[str].emit(): argument 1 has unexpected type 'QVariant'

I'm using anaconda 2.2.0 and have installed glue package and glue deps. Sorry if it's in a wrong place I am new to programming in general. Thank you.

**Comment by ChrisBeaumont** [comment]
Hi,

Can you provide some more information about how you started Glue? Is this from a terminal? from an IDE? Do you see any error/warning messages before this error? What operating system are you on?

This specific error suggests that some other graphical python library has switched to an old flavor of PyQT that Glue doesn't support. Spyder or PyCharm might do this, for example. 

There's no easy way fro glue to work with this old flavor of Qt, (QT API v 1) so the only option is to find a way to start glue without switching to the old flavor (this might just mean launching Glue from outside of the incompatible IDE, or configuring the IDE to use the newer version of QT)

**Comment by Techn0logic** [comment]
Hi Chris, thank you for your reply. Problem is fixed now after re-installing anaconda and glue and starting glue with:
 os.environ['QT_API'] = 'pyqt'
%gui qt

Great package, thank you

**Comment by ChrisBeaumont** [comment]
Great, glad to hear it!
