### ISSUE TITLE
Dead link in Docs

### ISSUE THREAD

**Issue by Gabriel-p** [glue-viz/glue#632]
Link:

http://www.glueviz.org/en/latest/getting_started/_static/w5.tgz

in http://www.glueviz.org/en/latest/getting_started/ is dead.

**Comment by ChrisBeaumont** [comment]
Hmm right, this should point to http://www.glueviz.org/en/latest/_static/w5.tgz

**Comment by astrofrog** [comment]
Sorry this was my fault when re-organizing the docs. Actually I think we can move ``w5.tgz`` inside ``getting_started``

**Comment by astrofrog** [comment]
Fixed by #678
