### ISSUE TITLE
Cannot find WCS information when primary HDU does not have the WCS

### ISSUE THREAD

**Issue by stscieisenhamer** [glue-viz/glue#642]
For FITS files, the wcs information is retrieved only from the primary HDU, as per data_factories.py:line#364, in function gridded_data.

If the FITS file has a non-data containing primary HDU, but otherwise have extensions with valid data + wcs information, subsequent operations in glue will error with index or other dimensionality errors because the non-existant wcs dimensions does not match the data dimensions. Or so it appears from the initial code examination.

Ideally, the WCS information would come from HDU's that successfully return from extract_data_fits.

**Comment by astrofrog** [comment]
@stscieisenhamer - I think this should now be fixed with the new FITS reader that you wrote. Thanks!
