### ISSUE TITLE
Provide unique string ID for datasets and components

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#646]
While developing a plugin, I realized that I really needed to have a dictionary where a dataset would be a key, but since Data is not immutable, that isn't possible. We could consider generating a UUID for each data object (in __iniit__) which would make it easier to refer to datasets by UUID.

**Comment by ChrisBeaumont** [comment]
This seems to work for me?

```python
In [1]: from glue.core import Data
In [2]: d = Data(x=[1,2,3])
In [3]: {d: 5}
Out[3]: {Data (label: ): 5}
```

**Comment by astrofrog** [comment]
Ok, I'm not sure why it wasn't working for me - closing!
