### ISSUE TITLE
Have (non-default) option to embed data in glu file

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#649]
In some cases, it might be useful to be able to embed data in session files. This should not be enabled by default, but would be nice as an option. An alternative would be to make glu files actually be folders instead with symbolic links to data files, and then users can choose to tar them up following links if they want.

**Comment by ChrisBeaumont** [comment]
Alyssa likes the igor model of two save formats -- a "lightweight" save file includes references to data dependencies, whereas a "packed" file is self-contained, and includes the data as well. 

For the tar route: when you tar a folder with a symbolic link and then untar it, do you get back a normal file inside the folder? If so then that's a nice option (assuming there's a python module that can perform the tar step on all platforms). Ideally we wouldn't require the user to manually tar files (and know about this "follow symlink" option which I didn't know about).

**Comment by astrofrog** [comment]
@ChrisBeaumont - for tar, it depends if you tarred it with the -h option (follow symbolic links). If you do that then when you expand again it puts the files right there and you don't get any links.

Python has tar and zip built-in, but we should check which has better cross-platform compatibility.

**Comment by astrofrog** [comment]
TarFile has a dereference option which is equivalent to the -h option: https://docs.python.org/3.5/library/tarfile.html#tarfile-objects

**Comment by ChrisBeaumont** [comment]
Cool, this sounds like a nice solution. In fact maybe we should always tar up the save file for convenience (a single file is easier to move around), and have glue support reading tarred files.

**Comment by ChrisBeaumont** [comment]
From the docs

> This has no effect on systems that do not support symbolic links.

I have no idea how windows behaves :)

**Comment by astrofrog** [comment]
Implemented in https://github.com/glue-viz/glue/pull/661
