### ISSUE TITLE
New mode: Drag an already existing subset

### ISSUE THREAD

**Issue by stscieisenhamer** [glue-viz/glue#651]
Modify an existing subset by dragging.

**Comment by ChrisBeaumont** [comment]
Note that this is already supported for the rectangle selector (but not the circle / polygon selectors)

**Comment by stscieisenhamer** [comment]
And that would explain why everyone thought such a capability existed, but since we've been myopic and looking at circular selections, never re-ran across it.

**Comment by ChrisBeaumont** [comment]
If I recall correctly this "feature" of draggable rectangles was introduced by accident while working on the spectral viewer, so enabling it for the other selectors should be pretty easy :)

**Comment by stscieisenhamer** [comment]
Whoa: handled with PR #657 so closing.
