### ISSUE TITLE
Provide for a meta attribute on Data and possibly Component

### ISSUE THREAD

**Issue by stscieisenhamer** [glue-viz/glue#654]
Use case is where the actual data being read in has more information that subsequently loaded plugins, viewers, clients, etc., may wish to use, but which the Data (and Component) objects themselves don't support.

**Comment by ChrisBeaumont** [comment]
This is a good idea. I think we have a units property on components, but it's hardly utilized and not comprehensive enough.

**Comment by astrofrog** [comment]
This has been done since this issue was opened - Data.meta exists
