### ISSUE TITLE
Make I/O more robust

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#658]
At the moment, if I select a dendrogram file for example, glue should be able to figure out to read it with the dendrogram reader because the file obeys a certain layout. That is, different readers/loaders should be able to say if they can recognize the file format, and should be given different priorities. So if both the HDF5 and the dendrogram reader can read a file, the more specialized format should win.

**Comment by ChrisBeaumont** [comment]
Note that the infrastructure for this already exists via the glue.config.data_factory `identifier` function, we just typically don't check for anything beyond file extension in these functions

**Comment by astrofrog** [comment]
@ChrisBeaumont - right, I was thinking of doing things similar to what we do in astropy where we can check for other things (and it's up to the loader to define whatever identification mechanism it wants). I think we should also consider adding priorities to make it deterministic.

**Comment by astrofrog** [comment]
@ChrisBeaumont - just for info I'm currently working on the data factory code for the various formats. Just one quick question - at the moment, we are using functions with attributes/callables:

```
    def dummy_factory(file_name):
        return glue.core.Data()
    dummy_factory.label = "Foo file"
    dummy_factory.identifier = has_extension('foo FOO')
    __factories__.append(dummy_factory)
    set_default_factory("foo", dummy_factory)
```

Any reason we couldn't switch to using classes?

**Comment by ChrisBeaumont** [comment]
I tend to prefer functions + decorators for things that users might want to override, since I think casual python users are more comfortable writing functions as opposed to classes. However, it would be easy to support both if there's something that would be much easier with a class.

Note also that the preferred way to write that code is something like

```
@data_factory("Foo file", has_extension("foo FOO")
def dummy_factory(file_name):
    return glue.core.Data()
```

(can't remember if set_default_factory can be specified via the decorator)

**Comment by astrofrog** [comment]
@ChrisBeaumont - ah yes, that looks good to. I think it would make sense to actually use the decorator notation internally too, since it's cleaner.

**Comment by astrofrog** [comment]
I mostly addressed this in various PRs over the past year.
