### ISSUE TITLE
Glue should auto-reshape outputs from linking functions

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#664]
Following up on the email thread on the glue user's group right now -- currently Glue requires that transformation functions return arrays whose shapes match the input arrays. We could be slightly more user-friendly about this, and reshape them automatically provided that they have the appropriate number of pixels.

**Comment by astrofrog** [comment]
This is now dealt with here: https://github.com/glue-viz/glue/blob/ef772b627b2748a8f0d9d4272d07068e47fea3ea/glue/core/component_link.py#L181
