### ISSUE TITLE
Refactor logic branches based on Component type -- use polymorphism instead

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#676]
From #601:

we should refactor logic branches in the viewers that look like:

```
if comp.categorical:
    state = CategoricalRoiSubsetState.from_range(comp, self.component, lo, hi)
else:
  ...
```
And instead add build_range_subset_state methods to the Component classes.

There are some other examples where we have logic branches based on comp.categorical, where we should follow a similar refactor

**Comment by JudoWill** [comment]
Read my mind @ChrisBeaumont

**Comment by astrofrog** [comment]
@JudoWill - did that in https://github.com/glue-viz/glue/pull/692
