### ISSUE TITLE
Select image pixels based on catalog

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#679]
Either this should be implemented, or if it is already possible, we should document it better.

@ChrisBeaumont - is this currently possible?

**Comment by ChrisBeaumont** [comment]
What do you mean specifically? I can think of three goals:

* make a spatial selection in catalog, use to filter pixels
* make a nonspatial selection in catalog, filter pixels that intersect selected points
* make a nonspatial selection in catalog, filter pixels in the convex hull defined by the selected points

The first works if the datasets are linked. The second two don't.

**Comment by astrofrog** [comment]
Just to clarify, I meant the second one.

**Comment by astrofrog** [comment]
This is the nearest neighbor linking mentioned in https://github.com/glue-viz/glue/issues/798, so closing this issue in favor of that one.
