### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#681]
@ChrisBeaumont - now that initial startup can (depending on installed plugins) be slower due to https://github.com/glue-viz/glue/pull/677, I was wondering if it would be good to reinstate a splash screen with a loading progress bar for plugins. Why was the splash screen removed initially? Did it not work with the mac app?

**Comment by ChrisBeaumont** [comment]
I loved the splash screen, but in hard-to-reproduce instances the mac app
would leave it up permanently. It'd be cool to figure out why

**Comment by astrofrog** [comment]
See https://github.com/glue-viz/glue/pull/694

**Comment by astrofrog** [comment]
Closed by https://github.com/glue-viz/glue/pull/694
