### ISSUE TITLE
Remove unused branches

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#684]
Currently there are 15 branches in the main repository:

https://github.com/glue-viz/glue/branches/all

The only ones I *think* are needed are ``master`` and ``stable``.

@ChrisBeaumont - are there any others we should keep? (e.g. feature branches you don't have in your fork?). What is the purpose of e.g. ``stsci_nightly``?

**Comment by ChrisBeaumont** [comment]
The `stsci*` branches were/are(?) used for stsci's internal dev builds of Ureka. We should probably keep them around (and update what they point to)

**Comment by astrofrog** [comment]
I've now cleaned things up.
