### ISSUE TITLE
sphinx link not resolved

### ISSUE THREAD

**Issue by hamogu** [glue-viz/glue#700]
On http://www.glueviz.org/en/stable/customizing_guide/configuration.html there is a 
`.. literalinclude:: scripts/coord_convert.py` which sphinx does not resolve. I assume it's something very simple like the file path is wrong or something like that.

**Comment by astrofrog** [comment]
Thanks, good catch! This was due to the use of a ``::`` before the literalinclude, hence why there was no Sphinx warning (otherwise Travis would have failed)
