### ISSUE TITLE
Loading dendrogram hdf5 file tries to open it as FITS?

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#701]
(using glue 0.5.1)
I tried importing an hdf5 file and got a slew of warnings in the terminal like this:
```
                                   ��F'�>3�G��p�2����G��H�K$i�;��7|��* [astropy.io.fits.card]
WARNING:astropy:The following header keyword is invalid or follows an unrecognized non-standard convention:
�"I�hQ��K�J����f��pNY'�Fxy�%\�rȴ4g
                                   ��F'�>3�G��p�2����G�
```
I strongly suspect that means glue is trying to load the .hdf5 file as a FITS file and reading all the binary data as FITS headers.  

Perhaps this means I should not try to read an hdf5 file directly?

**Comment by astrofrog** [comment]
I think the IO could be improved when it comes to dendrograms, and what you've seen above is certainly a bug - I'll take a look a this.

**Comment by astrofrog** [comment]
Working on this today.

**Comment by astrofrog** [comment]
Fixed in https://github.com/glue-viz/glue/pull/719
