### ISSUE TITLE
Plot options panel disappears when app is deselected

### ISSUE THREAD

**Issue by stscieisenhamer** [glue-viz/glue#705]
Situation:
- run glue, do an image viewer, and not that the image viewer plot options is visible.
- now select another application
- plot options hide
  Much inconvenient.

**Comment by ChrisBeaumont** [comment]
atm we clear this window whenever the current data viewer loses mouse focus (usually because another viewer gains mouse focus and repopulates the window right away). Maybe it's possible to configure this so that we only clear the window if another viewer is ready to repopulate it

**Comment by astrofrog** [comment]
This should now be fixed!
