### ISSUE TITLE
Move computation of data 'views' to Data objects

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#708]
As discussed by email with @ChrisBeaumont, in view of working with big data and remote data, it would be sensible to move the burden of computing some of the derived data products to Data objects. This would then allow sub-classes to use e.g remote servers to do the computation instead of doing this locally. Examples include:
- Computation of 1d histograms
- Computation of rasterized versions of scatter plots
- Computation of downsampled versions of images (e.g. using striding)

This would also allow us to experiment with having Data sub-classes that use e.g. GPUs or multi-threading to speed things up, or have data objects backed by local clusters.

**Comment by astrofrog** [comment]
Side note (before I forget) - glue currently uses ``axes.hist`` which in turn uses ``np.histogram`` - but that function is actually quite slow. The following function is at least 5x faster than ``np.histogram``:

```
def hist(values, bins, range):
    values = np.subtract(values, range[0])
    np.multiply(values, bins / (range[1] - range[0]), out=values)
    hist = np.bincount(values.astype(int), minlength=bins)
    return hist
```

anyway, just to say that this will be a good opportunity for some performance optimization.

**Comment by astrofrog** [comment]
Just for fun, I implemented a regular histogram function in Cython and for 1e8 values it runs in 0.3 seconds versus 9 seconds for np.histogram (used by matplotlib). For 1e9 values it runs in 5 seconds versus 90 seconds for np.histogram.

**Comment by astrofrog** [comment]
Side note again - I ended up opening a PR to Numpy to speed up histogram: https://github.com/numpy/numpy/pull/6100

**Comment by astrofrog** [comment]
Another note - this might also allow us to use e.g. yt to power a data object in the longer term, right?

**Comment by ChrisBeaumont** [comment]
> Another note - this might also allow us to use e.g. yt to power a data object in the longer term, right?

Yes (though all the uses of yt I've seen take O(minutes) to render, and I'm not sure if Glue's interface is well-suited to non-realtime viz)

**Comment by astrofrog** [comment]
Indeed the real-time aspect would be an issue, though I think that things like projection/rasterized maps are faster in yt than say volume rendering.

**Comment by astrofrog** [comment]
This is basically implemented in the form of the new base data interface:

http://docs.glueviz.org/en/latest/developer_guide/data.html

and there is even a prototype of a yt data object: https://github.com/glue-viz/glue-yt
