### ISSUE TITLE
Q: How does the new plugin architecture work with the OS X standalone instance of glue?

### ISSUE THREAD

**Issue by stscieisenhamer** [glue-viz/glue#709]
Question: Using the "new style" plugin architecture, where setuptools entry points are used by plugins to connect to glue, how are plugins to interact with the standalone version of glue?

Since the standalone version is its own python environment, I believe, installing a plugin package has no effect.

Does the user still need to put something, the relevant import/setup statements, in a local glue config.py file?

**Comment by astrofrog** [comment]
@stscieisenhamer - at the moment there is no clean way to install plugins into the MacOS X app. However, plugins can be bundled when we build the app, so we can bundle stable plugins. The main recommended way to install glue is via conda.

**Comment by stscieisenhamer** [comment]
*nod* just didn't know if there was trickery that might make it work. Thanks!
