### ISSUE TITLE
Specify core deps in the setup file

### ISSUE THREAD

**Issue by saimn** [glue-viz/glue#712]
Why are core dependencies not specified in the setup file (numpy, astropy, ...) ? I know conda is more hype today ;), but pip does the job to install glue, it would be better it is also installed the core deps.

**Comment by astrofrog** [comment]
Yes, we should probably include this, even if they can't all be installed by pip. Would you like to try and open a pull request to add these? (only absolute, not optional, requirements should be included)

**Comment by saimn** [comment]
Yes, I will look to propose a PR.

**Comment by saimn** [comment]
Hmm it seems that PyQt is not pip-installable, I thought it was. So the core dependencies are numpy, pandas, astropy and matplotlib ?

**Comment by astrofrog** [comment]
PyQt is definitely not pip-installable unfortunately. Yes, those are the right dependencies, and you should add PyQt anyway since it *is* required. If people have issues with pip installing it they will realize they have to install it another way first.

**Comment by saimn** [comment]
I don't see a valid PyQt package in pypi, there are packages for PyQt4 and PyQt5 but pip installing these gives an error even when PyQt is installed from the system site-package. So adding this to the requirements will probably create more issues than anything else. 
Are you fine with adding the install_requires without PyQt ? Otherwise we can close this issue, it is not critical for me. Also listing extra dependencies could be useful as well:
```
      install_requires=['numpy', 'pandas', 'astropy', 'matplotlib'],
      extras_require={
          'general':  ['dill', 'h5py', 'scipy', 'scikit-image'],
          'astro': ['PyAVM'],
          'export': ['plotly']
      },
```

**Comment by astrofrog** [comment]
@saimn - I guess that we could at least add all dependencies without Qt, and give the choice to the user as to whether to install PyQt4, PyQt5, or PySide. If you would like to open a pull request with something like what you are suggesting above, please feel free to :)
