### ISSUE TITLE
XLS / XLSX loader issue. 'Sheet1'

### ISSUE THREAD

**Issue by kmshort** [glue-viz/glue#713]
Hi there,

If you try to import an XLSX spreadsheet, and it doesn't have a worksheet called "Sheet1", GlueViz deals a "Could not lead data (wrong load method?)" "File load method: Excel" error.

1. The loader should load the first sheet in the worksheet, regardless of its name. xlrd has methods to do this, e.g.
xl_workbook = xlrd.open_workbook(filename)
xl_sheet = xl_workbook.sheet_by_index(0)

2. While on this, other sheets are seeminly ignored. It would be nice to define what sheet is loaded. That could start with something like:
sheet_names = xl_workbook.sheet_names()
then use the sheet names list to enable selection of one of them and open it with something akin to:
xl_sheet = xl_workbook.sheet_by_name(sheet_names[0])

Anyway, I hope this report is of use.

the bits of code here are taken from https://blogs.law.harvard.edu/rprasad/2014/06/16/reading-excel-with-python-xlrd/

thanks

**Comment by astrofrog** [comment]
Thanks for the report! Let us know if you would be interested in helping make some modifications to the Excel reader to fix these issues (otherwise I can look into it in the near future)

**Comment by astrofrog** [comment]
@kmshort - I am having trouble reproducing this issue. Could you send me the spreadsheet you are using?

**Comment by astrofrog** [comment]
Ah no ignore me, I can reproduce the issue
