### ISSUE TITLE
Explore alternative frameworks to speed up scatter plots

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#722]
We should explore the use of VisPy and PyQtGraph to make scatter plots. This issue is to keep track of findings related to this.
- Vispy: currently the axes are not very esthetically pleasing, though they were only implemented recently. I opened an issue here to ask if we can customize the appearance: https://github.com/vispy/vispy/issues/1057
- PyQtGraph: fast for line plots, but super slow for scatter plots. I've opened an issue here to find out why: https://github.com/pyqtgraph/pyqtgraph/issues/217

**Comment by astrofrog** [comment]
cc @nmearl @stscieisenhamer @ibusko, in case you have any insight relating to PyQtGraph and performance

**Comment by astrofrog** [comment]
Just for info, PyQtGraph, while fast for lines, is not going to work for scatter plots: https://github.com/pyqtgraph/pyqtgraph/issues/217

**Comment by nmearl** [comment]
Indeed. While fast scatter plots are possible in PyQtGraph using OpenGL (specifically, the GLScatterPlotItem widget), the author has indicated that the pipeline will be replaced with VisPy.

>The 3D graphics system in pyqtgraph is composed of a view widget and several graphics items (all subclasses of GLGraphicsItem) which can be added to a view widget.

>Note 1: pyqtgraph.opengl is based on the deprecated OpenGL fixed-function pipeline. Although it is currently a functioning system, it is likely to be superceded in the future by VisPy.

>Note 2: use of this system requires python-opengl bindings. Linux users should install the python-opengl packages from their distribution. Windows/OSX users can download from http://pyopengl.sourceforge.net.

**Comment by nmearl** [comment]
As a side note, you can get some pretty good performance gains by enabling down sampling and view clipping.

```python
 import pyqtgraph as pg
 import numpy as np
 
 pw = pg.plot(title="Testing")
 pw.setDownsampling(ds=True, auto=True, mode='peak')
 pw.setClipToView(True)
 pw.plot(np.arange(1e5), np.random.sample(1e5), symbol='o')
```

**Comment by astrofrog** [comment]
Also requested in https://github.com/glue-viz/glue/issues/403, and the official issue to keep track of this is https://github.com/glue-viz/glue-vispy-viewers/issues/138.

**Comment by astrofrog** [comment]
This isn't so much of a problem anymore now with the scatter density plots, so closing
