### ISSUE TITLE
Release glueviz 0.6

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#744]
I think it would be nice to have a reasonably fast release cycle so that people can start using some of the new features. The following is a list of blockers for this release (will be updated)

* [x] write 'What's new in 0.6' page
* [x] save loaded plugins in session file

**Comment by astrofrog** [comment]
@ChrisBeaumont - would you have any objections to dropping support for Python 2.6 in this release?

**Comment by ChrisBeaumont** [comment]
Dropping 2.6 is fine by me. I think restoring the demo custom viewers and
docs should be a blocker.

**Comment by astrofrog** [comment]
@ChrisBeaumont - yes, I agree, will take a look this evening.

**Comment by astrofrog** [comment]
@ChrisBeaumont - when you say 'docs', you meant in the context of the custom viewers?

**Comment by astrofrog** [comment]
0.6 has been released! :tada:

Now waiting for the conda package to be updated (#725) before announcing.
