### ISSUE TITLE
Example data viewer code is broken

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#750]
In the [example data viewer repo](https://github.com/glue-viz/example_data_viewers), none of the demos are properly registering the custom viewers. I haven't dug into why, but these demos (and perhaps the documentation on custom viewers) appears to be out of date with glue's current registration process

**Comment by astrofrog** [comment]
@ChrisBeaumont - thanks for spotting that, I can look into it later this week.

**Comment by astrofrog** [comment]
That's weird, it works for me for the earthquake one for example. I go inside the earthquake directory, and type ``glue earthquakes.csv`` and it opens up, then I can select the earthquake viewer. At which point does this fail for you? Similarly, going in the basketball_shotcharts directory and typing ``glue shots.csv`` works.

**Comment by ChrisBeaumont** [comment]
Ah ok, this was due to having an old `config.py` file in `~/.glue` that did something to prevent plugins from being loaded. Once I removed that things are working again.

This can probably be closed as a non-bug, since most people won't have old config.py files causing problems.
