### ISSUE TITLE
the help menu in the glue script is too old

### ISSUE THREAD

**Issue by teuben** [glue-viz/glue#763]
1) There is no help->about to say what version of glue this is.

and related:

2) help->online documentation goes to    http://www.glue-viz.org/en/latest/
but this seems to refer to some old 0.1 version???
Instead http://www.glueviz.org/en/latest/ seems to be more up to date,
and point to 0.4.0.  
Oddly, http://www.glueviz.org/en/stable/ also has this version. So that's odd. 
Should one of them not point to 0.5.3 ?

**Comment by ChrisBeaumont** [comment]
Weird, so glue-viz is always supposed to redirect to glueviz, but that isn't always happening:

```
glue-viz.org -> www.glueviz.org
glue-viz.org/en/latest -> http://www.glueviz.org/en/latest
glue-viz.org/foo/bar -> http://www.glueviz.org/foo/bar
www.glue-viz.org -> http://www.glue-viz.org/en/latest/
```

That last redirect is wrong (and I'm not even sure where the old content at http://www.glue-viz.org/en/latest/ is coming from!)

**Comment by ChrisBeaumont** [comment]
It looks like readthedocs was configured to host an old version of the docs with www.glue-viz.org. I've tried deleting that config, to see if it fixes the redirect

**Comment by ChrisBeaumont** [comment]
@teuben @astrofrog 

> Instead http://www.glueviz.org/en/latest/ seems to be more up to date,
and point to 0.4.0.

It looks like (https://github.com/glue-viz/glue/blob/master/doc/conf.py#L80) the listed version on the latest sphinx docs is still 0.4.0 -- so I suspect that `en/latest` is actually on 0.6.0.dev, even though it lists the same version number
