### ISSUE TITLE
plugin manager can accumulate stale entries?

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#764]
I tried uninstalling and reinstalling the volume plugin. While the plugin was uninstalled, I still saw the vispy volume renderer as an option in the "manage plugins" window. How is that list computed? Does it remove entries appropriately?

**Comment by astrofrog** [comment]
Ah yes, it's added to ``.glue/plugins.cfg``, need to think about how to deal with uninstalled plugins.

**Comment by astrofrog** [comment]
Fixed in #776 - now only installed plugins are shown in the plugin manager
