### ISSUE TITLE
Implement GlueComboBox.findData

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#774]
... and make sure GlueComboBox is used in all widgets.

See https://github.com/glue-viz/glue/pull/755#discussion_r42766649

**Comment by ChrisBeaumont** [comment]
I can reproduce the PySide bug on my machine as well. I can also seem to fix it (needs more testing to be sure) by patching QComboBox.findData in `external.qt._load_pyside`:

```diff
--- a/glue/external/qt.py
+++ b/glue/external/qt.py
@@ -206,6 +206,13 @@ def _load_pyside():
     global QT_API
     QT_API = QT_API_PYSIDE
 
+    def findData(self, value):
+        for i in range(self.count()):
+            if self.itemData(i) == value:
+                return i
+        return -1
+    QtGui.QComboBox.findData = findData
+
     deny_module('PyQt4')
     deny_module('PyQt5')
```

**Comment by astrofrog** [comment]
@ChrisBeaumont - I've implemented a fix for this and also more generally an alternative to ``GlueComboBox`` in https://github.com/glue-viz/qt-helpers/pull/5.

**Comment by astrofrog** [comment]
Fixed in https://github.com/glue-viz/glue/pull/822
