### ISSUE TITLE
glue sessions files do not automatically get the .glu extension

### ISSUE THREAD

**Issue by teuben** [glue-viz/glue#785]
When I saved a session, i just typed "session1", and despite that it says "Glue Session" as the file type, no extension was added in the end. Opening that session again via the GUI then became "impossible" as it could not find this. Of course restarting with -g probably would have worked. It certainly wasn't obvious to me at this stage that .glu is the extension that is needed for glue to find those files.

**Comment by astrofrog** [comment]
This is already fixed in master - are you using the latest stable version, or latest developer version from the github repository?

**Comment by astrofrog** [comment]
@teuben this should have been done in https://github.com/glue-viz/glue/pull/729 - but feel free to re-open if it does not work with the developer version or 0.6 once it's out.
