### ISSUE TITLE
setup.py install does not recognized numpy development version

### ISSUE THREAD

**Issue by mherkazandjian** [glue-viz/glue#819]
in master

      python setup.py install

tries downloading and installing numpy 1.10.4 although there is the developement version of numpy installed. is there a way to prevent glueviz setup not to download numpy 1.10.4?

**Comment by astrofrog** [comment]
What do you get if you do:

```
python -c 'import numpy; print(numpy.__version__); print(numpy.__path__)'
```

?

**Comment by mherkazandjian** [comment]
1.11.0.dev0+6d323ae
['/data/python2.7/site-packages/numpy']

**Comment by mherkazandjian** [comment]
maybe in the check for the version the first three tokens must be kept, i.e 1.11.0 and the .dev0-githash discarded

**Comment by astrofrog** [comment]
Glue doesn't actually check the versions, we only supply ``install_requires=['numpy', ...]`` and setuptools appears to be installing Numpy even though it's already there. I'll see if I can replicate this. It could be a setuptools issue.

**Comment by astrofrog** [comment]
What operating system are you using? When I run:

```
python setup.py install
```

I get the following after glue itself has installed:

```
Using /Users/tom/miniconda3/envs/production/lib/python3.4/site-packages
Searching for numpy==1.11.0.dev0+8a76291
Best match: numpy 1.11.0.dev0+8a76291
Adding numpy 1.11.0.dev0+8a76291 to easy-install.pth file
```

Do you see the line ``searching for numpy==...`` in the install log?

**Comment by mherkazandjian** [comment]
ok. seems to be a problem with numpy. i pulled the latest dev and it works fine.
