### ISSUE TITLE
Should dialog to open files be relative to working directory?

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#848]
See https://groups.google.com/forum/#!topic/glue-viz/hSZyC-yVwak

**Comment by nilswagner** [comment]
+1 for current i.e. working directory.

**Comment by pllim** [comment]
I was just going to open an issue to complain about `File -> Open Data Set` does not recognize the current working directory, but rather is using the "last used" directory... I am also :+1: for working directory.

**Comment by pllim** [comment]
Potential fix in #1106.
