### ISSUE TITLE
Dendrogram not available for v0.7 release of Glue

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#893]
I followed the instruction on the GlueViz website and add the following code into ~/.glue/config.py

`from glue.qt.widgets import enable_dendrograms`
`enable_dendrograms()`

While I got an error as 

` /Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.7.0.dev25372537-py2.7.egg/glue/qt/__init__.py:6: GlueDeprecationWarning: The glue.qt subpackage is deprecated - see the v0.7 release announcement for more details`

Any solutions for this problem? Thanks!

P.S. Maybe the online instruction of using dendrogram should be updated with the new release of Glue :)

**Comment by astrofrog** [comment]
Instructions on the website have been updated :)
