### ISSUE TITLE
Region of interest bug not displaying in some image (and very slow?)

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#894]
This bug was discovered during the Glue tutorial at Python in Astronomy 2016. I have shared the files with @astrofrog privately. Here is the workflow:
1. Use Image Viewer to display `s1_mips_v0.30_sci.fits` (Viewer 1).
2. Use another Image Viewer to display `s12_ch1_v0.30_sci.fits` (Viewer 2).
3. Open `s12_ch1_v0.30_sci.fits` again in Viewer 1 (so this image is now on both viewers).
4. Use circular region of interest tool to select a star.

You will notice that:
1. It is very slow? It was on my Windows 7 laptop.
2. The region appears on both viewers initially. But when you switch displayed image on Viewer 1 from `s1_mips...` to `s12_ch1...`, the region disappears on Viewer 1.

**Comment by pllim** [comment]
Update: I deleted the original region of interest and made another one. Now the mask does not appear on `s12_ch1...` on the other viewer.

**Comment by astrofrog** [comment]
I think these issues should be fixed now (in the upcoming glue v0.11). I'll close this, but feel free to re-open if you are still seeing this with the latest developer version (or v0.11 once it's out).
