### ISSUE TITLE
Minor visual misfeatures

### ISSUE THREAD

**Issue by r-owen** [glue-viz/glue#895]
When viewing a FITS image using `vispy` as a backend (I assume; it's whatever glue defaulted to) I find a few minor glitches:
- When I select stretch and functional transform in the contrast menu the menu does not show my settings if I go back. It would be nice to be able to see the current settings, since I may not remember and it can inform my next attempt to improve the display.
- When I click on the contrast tool it highlights without showing me the menu. This appears to be intentional (going into a mode where I can manually drag to change contrast), but is rather surprising. Please consider showing a menu where one option is drag-to-change and one is to reset to the default (as if the user never dragged). Or add a tool -- one toggles, one has a menu?

**Comment by astrofrog** [comment]
The UI for this has been re-designed, and both issues are resolved
