### ISSUE TITLE
Large FITS files crash glue on startup

### ISSUE THREAD

**Issue by Cadair** [glue-viz/glue#898]
I tried to open a 15GB file, it crashed hard.

**Comment by astrofrog** [comment]
@Cadair - can you share the file? I want to try and reproduce the issue locally. I'm trying to figure out whether there are some conditions under which memory mapping doesn't work.

**Comment by Cadair** [comment]
I can share if you have somewhere I can deposit a 12GB (compressed) file.

**Comment by astrofrog** [comment]
I'm going to close this - I think I eventually tracked it down to a memory mapping issue on certain Linux distributions which is beyond our control.
