### ISSUE TITLE
Linking Pixel Axis From 1D Array to Pixel Axis of 2D Array

### ISSUE THREAD

**Issue by dborncamp** [glue-viz/glue#917]
I am trying to link the Y axis of a 2 dimensional array (attached file: col100_sci.txt) to the index of a 1 dimensional array (attached file f100.txt). I was hoping that when I select something in the 1 dimensional file I could get the corresponding rows highlighted.

This was read in using the `qglue` interface from `ipython`. The data originated from an open HDF5 file but it was casted to numpy arrays before opening qglue.

[f100.txt](https://github.com/glue-viz/glue/files/198950/f100.txt)
[col100_sci.txt](https://github.com/glue-viz/glue/files/198951/col100_sci.txt)

**Comment by astrofrog** [comment]
@dborncamp - what format are the files attached here? (they seem to be in a binary format)

I just tried to launch glue with two random datasets:

```
qglue(data1d=np.random.random(100), data2d=np.random.random((100,3)))
```

I then linked ``Pixel y`` to ``Pixel Axis 0`` and it seems to work as expected provided that the selection is done with a x or y range selection (only possible in scatter plots).

However, I need to look into it further to understand the limitations of doing this, and where it no longer works.

**Comment by dborncamp** [comment]
These were originally read in as hdf5 datasets but they were casted to numpy arrays. The attached files were those datasets written with numpy.tofile(). Do you need the files in a different format?

**Comment by astrofrog** [comment]
@dborncamp - it might be easier if you could write them out to FITS - ``tofile`` just writes out the array as raw bytes and I think it loses information about e.g. shape (``np.save`` would be more robust)

**Comment by dborncamp** [comment]
@astrofrog - Sorry for the long reply. git will not allow me to upload the files in fits or tar format so they should be attached in zip format.

[GlueIssue.zip](https://github.com/glue-viz/glue/files/217356/GlueIssue.zip)

**Comment by astrofrog** [comment]
@dborncamp - sorry for the delay - I've had a chance to look into this in more detail, and this can be fixed by using element-to-element linking between datasets. There is not yet a GUI way to set this up (I'm working on it), but in the mean time you can use ``join_on_key``:

```
from glue import qglue
from glue.core.data_factories import load_data

col100 = load_data('col100_sci.fits')
f100 = load_data('f100.fits')

col100.join_on_key(f100, 'Pixel y', 'Pixel Axis 0')

qglue(col100=col100, f100=f100)
```

I think this should do what you want?

**Comment by astrofrog** [comment]
More details about join_on_key here: http://glueviz.org/en/stable/api/glue.core.data.Data.html?highlight=join_on_key#glue.core.data.Data.join_on_key

**Comment by astrofrog** [comment]
Closing this since this was resolved
