### ISSUE TITLE
Where is the Quit menu item?

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#921]
I was expecting to find `File -> Quit` to quit the application, but it is not there on Linux and Windows. The only way to close it is by clicking the "X" on upper right corner, or `Alt + F4` (Windows only).

**Comment by astrofrog** [comment]
@pllim - I noticed this too, I think the reason we didn't add it is because on Mac the 'python' menu includes 'Quit'. But I think we should probably add it to 'File' too. Would you like to do a PR to add this?

**Comment by pllim** [comment]
When I dabbled in cross-platform Qt application two years back, I had to hack around that pesky Mac menu. Yeah, I can get my hands sticky in this Glue issue but I am not sure when I have time. This is not urgent, right?

**Comment by astrofrog** [comment]
@pllim - no, it's not urgent, so whenever you have time :) The relevant place to look will be ``glue/app/qt/application.py`` - thanks!
