### ISSUE TITLE
3D rendering not working properly on Windows?

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#923]
I used 3D rendering on the test image, `L1448_13CO.fits`, that was provided by @astrofrog . It works on Linux and Mac, albeit not very eye-friendly (see #922). When I do the same on Windows, the 3D bounding box shows up, but no data points (the default points color is also set to black, but nothing appears even when I change that to something else).

Here is the graphics card info for NVS 5200M that might or might not be relevant:

```
OS: Windows 7 Enterprise 64-bit (SP1)
DirectX runtime version: 11.0
NVIDIA driver: 340.84
Direct3D API: 11
Direct3D feature level: 11_0
CUDA Cores: 96
Graphics clock: 672 MHz
Processor clock: 1344 MHz
Memory data rate: 3138 MHz
Memory interface: 64-bit
Memory bandwidth: 25.10 GB/s
Total available graphics memory: 4095 MB
Dedicated video memory: 1024 MB GDDR5
System video memory: 0 MB
Shared system memory: 3071 MB
(the rest is hardware config like BIOS, IRQ, etc.)
```

**Comment by astrofrog** [comment]
@pllim - are there any warnings in the console from which you are starting Glue?

**Comment by pllim** [comment]
@astrofrog , somehow when I start Glue from Anaconda Command Prompt on Windows, the terminal seems to push the app into background (i.e., I get the prompt back). So, I cannot be sure whether errors/warnings that are supposed to appear on terminal window get lost or not. Other than that, I don't see any popup message (like I did with the corrupted FITS files) to indicate errors.

Is there a way to capture everything in a log file?

**Comment by astrofrog** [comment]
@pllim - some errors get logged to the console which you can get to in View -> Console Log. Do you see anything in there? I'll look into whether we can set up file-based logging.

**Comment by pllim** [comment]
Ah, yes. I see this:

```python
...\jupyter_client\localinterfaces.py:242: UserWarning: Unexpected error discovering local network interfaces: [Error 6] The handle is invalid

warn("Unexpected error discovering local network interfaces: %s" % e)

Traceback (most recent call last):

File "...\glueviz-0.8.0.dev2650-py2.7.egg\glue\core\qt\layer_artist_model.py", line 207, in rowsInserted

parent.on_artist_add(self.model().artists)

File "...\glueviz-0.8.0.dev2650-py2.7.egg\glue\core\qt\layer_artist_model.py", line 312, in on_artist_add

self.layout_style_widgets[layer_artist] = self.layer_style_widget_cls(layer_artist)

File "...\glue_vispy_viewers\volume\layer_style_widget.py", line 49, in __init__

self._update_limits()

File "...\glueviz-0.8.0.dev2650-py2.7.egg\glue\external\echo.py", line 268, in __exit__

p.notify(self.instance, old, new)

File "...\glueviz-0.8.0.dev2650-py2.7.egg\glue\external\echo.py", line 87, in notify

cback(new)

File "...\glueviz-0.8.0.dev2650-py2.7.egg\glue\utils\misc.py", line 57, in result

return func(*args, **kwargs)

File "...\glue_vispy_viewers\volume\layer_artist.py", line 145, in _update_data

self._multivol.set_data(self.id, np.nan_to_num(data))

File "...\glue_vispy_viewers\volume\volume_visual_legacy.py", line 196, in set_data

self._update_scaled_data(label)

File "...\glue_vispy_viewers\volume\volume_visual_legacy.py", line 207, in _update_scaled_data

self._program['u_volumetex_{0:d}'.format(index)].set_data(data)

File "...\vispy\gloo\texture.py", line 741, in set_data

self._update_variables()

File "...\vispy\gloo\texture.py", line 716, in _update_variables

self._glsl_sample['c'] = self._c

File "...\vispy\visuals\shaders\function.py", line 243, in __setitem__

variable.value = val

File "...\vispy\visuals\shaders\variable.py", line 119, in value

(type(value), self))

TypeError: Unknown data type <type 'long'> for variable <Variable "uniform int u_c" at ...>
```

**Comment by astrofrog** [comment]
@pllim - thanks, this is helpful, I'll try and see if there's an easy fix

**Comment by shichuzhu** [comment]
I have the same issue on my Windows 7 laptop. 3D plots show up fine on another Windows 10 desktop.

**Comment by astrofrog** [comment]
@shichuzhu - what version of glue-vispy-viewers do you have?

**Comment by shichuzhu** [comment]
@astrofrog Here are my version info from the help menu:
Glue: 0.10.4
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.2
PySide: Not installed
qtpy: 1.2.1
setuptools: 27.2.0
numpy: 1.12.1
matplotlib: 2.0.2
pandas: 0.20.1
astropy: 1.3.2
dill: 0.2.6
h5py: 2.7.0
xlrd: 1.0.0
glue_vispy_viewers: 0.7.2
IPython: 5.3.0
qtconsole: 4.3.0
ipykernel: 4.6.1
traitlets: 4.3.2
pygments: 2.2.0
zmq: 16.0.2
scipy: 0.19.0
skimage: 0.13.0
pyavm: Not installed
spectral_cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: 3.0.7
plotly: Not installed

I installed from Anaconda 4.4.0 (64-bit) with python version 3.6.1

**Comment by astrofrog** [comment]
@pllim @shichuzhu - this was fixed in https://github.com/glue-viz/glue-vispy-viewers/pull/245, so I'll close this. However, feel free to open a new issue if you are still having problems with the latest stable version of glue!
