### ISSUE TITLE
define new component with np requires config.py

### ISSUE THREAD

**Issue by sean-lockwood** [glue-viz/glue#948]
If the user does not have a ~/.glue/config.py file containing an import for numpy, then they are unable to define new components containing np in the expressions.

**Comment by sean-lockwood** [comment]
In core/parse.py, the global environmental variables don't necessarily include np.  Perhaps import it and add it to the env list there?

**Comment by astrofrog** [comment]
@sean-lockwood - good idea - I'm working on this here: https://github.com/glue-viz/glue/pull/956 (I'm going to make some more improvements before merging it)

**Comment by astrofrog** [comment]
@sean-lockwood - I've now merged in some changes that make it possible to use ``numpy``, ``np``, and ``math``. You can either try the latest developer version of glue, or I will release 0.8 soon which will include these changes. Let me know if you run into any issues!
