### ISSUE TITLE
Launching glue from iPython notebooks – docs update?

### ISSUE THREAD

**Issue by bmorris3** [glue-viz/glue#961]
The [docs](http://glueviz.org/en/stable/faq.html#how-do-i-use-glue-with-the-ipython-notebook) currently suggest launching iPython notebooks with `ipython notebook --gui qt` to interactively update glue sessions from the notebook. However with iPython v4.0.3, `--gui` has been deprecated, so I think the right way to do this is to use the `%qui qt` magic within a notebook. 

Is that the appropriate way to launch glue sessions from the notebook for iPython>4, and should I update the docs accordingly? I'd be happy to make the tiny PR if that's the correct way to do it.

**Comment by astrofrog** [comment]
@bmorris3 - yes, that's correct - please go ahead with the small PR!

**Comment by astrofrog** [comment]
Fixed in https://github.com/glue-viz/glue/pull/1233
