### ISSUE TITLE
Some SubsetState classes are missing from the docs

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#973]
The API docs for ``glue.core.subset`` is missing a number of classes:

http://glueviz.org/en/stable/developer_guide/api.html#id6

(e.g. ``MaskSubsetState)

Basically someone needs to go through ``glue/core/subset.py`` and list all the classes in:

```
__all__ = ['Subset', 'SubsetState', 'RoiSubsetState', 'CompositeSubsetState',
           'OrState', 'AndState', 'XorState', 'InvertState',
           'ElementSubsetState', 'RangeSubsetState', 'combine_multiple']
```

at the top of the file.

@PennyQ - would you like to work on this?

**Comment by PennyQ** [comment]
@astrofrog Yeah sure, is it for add the missing instructions of `Classes` in `glue.core.subset Module`? Could you show me how to do it?

**Comment by astrofrog** [comment]
> Yeah sure, is it for add the missing instructions of Classes in glue.core.subset Module

No, it's just to add a few classes to the list - you can get the details by clicking on them. So the job here is just to make sure all the classes are listed. As mentioned above, the list of classes in that table is given by the classes in the ``__all__`` list shown above, so all you need to do is go through ``glue/core/subset.py`` and make sure all the classes are listed in the ``__all__`` list at the top.

You can test whether it worked by installing the development version of glue you are modifying, then go into the doc folder and type ``make html``, and the documentation will be built inside ``doc/_build/html/index.html``

**Comment by astrofrog** [comment]
Ah but if you want you can also add more descriptions for the classes that are already there (the second column in the table). To do that, you need to add docstrings with one sentence describing what the class is - maybe you can do it for the ones you can figure out, and let me know if there are any that you don't know, and I can help.

**Comment by astrofrog** [comment]
Thanks @PennyQ!
