### ISSUE TITLE
Switch combobox items name and labels for image viewer?

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#990]
It may make more sense to use `x, y, slice` as the combobox label and real dataset column name in the combobox (as shown below), while I check the code in [image widget_viewer](https://github.com/glue-viz/glue/blob/master/glue/viewers/image/qt/viewer_widget.py) and couldn't find the lines to work on this, could you show me how to do it @astrofrog ? Thanks!

![image](https://cloud.githubusercontent.com/assets/13411839/15339430/69e66922-1c52-11e6-806c-a1c6508d7099.png)

**Comment by astrofrog** [comment]
@PennyQ - if we do that we need to also do a bit of work to make sure we show the correct sliders when there are 4+ dimensions. This is all done I believe in:

https://github.com/glue-viz/glue/blob/master/glue/viewers/common/qt/data_slice_widget.py

**Comment by astrofrog** [comment]
An I agree that listing it as:

x:
y:
slices:

makes more sense.

**Comment by PennyQ** [comment]
@astrofrog Hmmm I didn't expect this would be a more complicated question, I thought it's just change the text for both labels and combobox, and my current problem is that I couldn't find the codes to assign the text to both. Would you prefer to show me where I can start or you could take care of it? :)

**Comment by astrofrog** [comment]
Done in the re-written image viewer :)
